In [4]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [58]:
response = requests.get('https://en.wikipedia.org/wiki/List_of_largest_universities')
response.content

b'<!DOCTYPE html>\n<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available" lang="en" dir="ltr">\n<head>\n<meta charset="UTF-8">\n<title>List of largest universities - Wikipedia</title>\n<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split(\'%2C\').forEach(function(pref){className=className.replace(new RegExp(\'(^| )\'+pref.replace(/-clientpref-\\w+$|[^\\w-]+/g,\'\')+\'-clientpref-\\\\w+( |$)\'),\'$1\'+pref+\'$2\');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"17eedded-6bbe-41df-89d4-185f1a2ff066","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_universities","wgTitle":"List of largest universities","wgCurRevisionId":1276835439,"wgRevisionId":1276835439,"wgArticleId":41435822,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["CS1 Japanese-language sources (ja)","CS1 Lithuanian-language sources (lt)","Articles with short description","Short description is different from Wikidata","Articles needing additional references from January 2015","All articles needing additional references","Lists of universities and colleges by country","Lists of education-related superlatives"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_universities","wgRelevantArticleId":41435822,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgCiteReferencePreviewsActive":false,"wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":20000,"wgEditSubmitButtonLabelPublish":true,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q17098461","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false};\nRLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","ext.wikimediamessages.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.tablesorter","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","ext.checkUser.clientHints","ext.quicksurveys.init","ext.growthExperiments.SuggestedEditSession"];</script>\n<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\\\","watchToken":"+\\\\","csrfToken":"+\\\\"});\n}];});});</script>\n<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022">\n<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>\n<meta name="ResourceLoaderDynamicStyles" content="">\n<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022">\n<meta name="generator" content="MediaWiki 1.44.0-wmf.23">\n<meta name="referrer" content="origin">\n<meta name="referrer" content="origin-when-cross-origin">\n<meta name="robots" content="max-image-preview:standard">\n<meta name="format-detection" content="telephone=no">\n<meta name="viewport" content="width=1120">\n<meta property="og:title" content="List of largest universities - Wikipedia">\n<meta property="og:type" content="website">\n<link rel="preconnect" href="//upload.wikimedia.org">\n<link rel="alternate" media="only screen and (max-width: 640px)" href="//en.m.wikipedia.org/wiki/List_of_largest_universities">\n<link rel="alternate" type="application/x-wiki" title="Edit this page" href="/w/index.php?title=List_of_largest_universities&amp;action=edit">\n<link rel="apple-touch-icon" href="/static/apple-touch/wikipedia.png">\n<link rel="icon" href="/static/favicon/wikipedia.ico">\n<link rel="search" type="application/opensearchdescription+xml" href="/w/rest.php/v1/search" title="Wikipedia (en)">\n<link rel="EditURI" type="application/rsd+xml" href="//en.wikipedia.org/w/api.php?action=rsd">\n<link rel="canonical" href="https://en.wikipedia.org/wiki/List_of_largest_universities">\n<link rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">\n<link rel="alternate" type="application/atom+xml" title="Wikipedia Atom feed" href="/w/index.php?title=Special:RecentChanges&amp;feed=atom">\n<link rel="dns-prefetch" href="//meta.wikimedia.org" />\n<link rel="dns-prefetch" href="auth.wikimedia.org">\n</head>\n<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_universities rootpage-List_of_largest_universities skin-vector-2022 action-view"><a class="mw-jump-link" href="#bodyContent">Jump to content</a>\n<div class="vector-header-container">\n\t<header class="vector-header mw-header">\n\t\t<div class="vector-header-start">\n\t\t\t<nav class="vector-main-menu-landmark" aria-label="Site">\n\t\t\t\t\n<div id="vector-main-menu-dropdown" class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right"  title="Main menu" >\n\t<input type="checkbox" id="vector-main-menu-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-main-menu-dropdown" class="vector-dropdown-checkbox "  aria-label="Main menu"  >\n\t<label id="vector-main-menu-dropdown-label" for="vector-main-menu-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>\n\n<span class="vector-dropdown-label-text">Main menu</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\t\t<div id="vector-main-menu-unpinned-container" class="vector-unpinned-container">\n\t\t\n<div id="vector-main-menu" class="vector-main-menu vector-pinnable-element">\n\t<div\n\tclass="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned"\n\tdata-feature-name="main-menu-pinned"\n\tdata-pinnable-element-id="vector-main-menu"\n\tdata-pinned-container-id="vector-main-menu-pinned-container"\n\tdata-unpinned-container-id="vector-main-menu-unpinned-container"\n>\n\t<div class="vector-pinnable-header-label">Main menu</div>\n\t<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>\n\t<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>\n</div>\n\n\t\n<div id="p-navigation" class="vector-menu mw-portlet mw-portlet-navigation"  >\n\t<div class="vector-menu-heading">\n\t\tNavigation\n\t</div>\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t<li id="n-mainpage-description" class="mw-list-item"><a href="/wiki/Main_Page" title="Visit the main page [z]" accesskey="z"><span>Main page</span></a></li><li id="n-contents" class="mw-list-item"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li id="n-currentevents" class="mw-list-item"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li id="n-randompage" class="mw-list-item"><a href="/wiki/Special:Random" title="Visit a randomly selected article [x]" accesskey="x"><span>Random article</span></a></li><li id="n-aboutsite" class="mw-list-item"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li id="n-contactpage" class="mw-list-item"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n\t\n<div id="p-interaction" class="vector-menu mw-portlet mw-portlet-interaction"  >\n\t<div class="vector-menu-heading">\n\t\tContribute\n\t</div>\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t<li id="n-help" class="mw-list-item"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li id="n-introduction" class="mw-list-item"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li id="n-portal" class="mw-list-item"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li id="n-recentchanges" class="mw-list-item"><a href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]" accesskey="r"><span>Recent changes</span></a></li><li id="n-upload" class="mw-list-item"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li id="n-specialpages" class="mw-list-item"><a href="/wiki/Special:SpecialPages"><span>Special pages</span></a></li>\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n</div>\n\n\t\t\t\t</div>\n\n\t</div>\n</div>\n\n\t\t</nav>\n\t\t\t\n<a href="/wiki/Main_Page" class="mw-logo">\n\t<img class="mw-logo-icon" src="/static/images/icons/wikipedia.png" alt="" aria-hidden="true" height="50" width="50">\n\t<span class="mw-logo-container skin-invert">\n\t\t<img class="mw-logo-wordmark" alt="Wikipedia" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;">\n\t\t<img class="mw-logo-tagline" alt="The Free Encyclopedia" src="/static/images/mobile/copyright/wikipedia-tagline-en.svg" width="117" height="13" style="width: 7.3125em; height: 0.8125em;">\n\t</span>\n</a>\n\n\t\t</div>\n\t\t<div class="vector-header-end">\n\t\t\t\n<div id="p-search" role="search" class="vector-search-box-vue  vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box">\n\t<a href="/wiki/Special:Search" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" title="Search Wikipedia [f]" accesskey="f"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>\n\n<span>Search</span>\n\t</a>\n\t<div class="vector-typeahead-search-container">\n\t\t<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">\n\t\t\t<form action="/w/index.php" id="searchform" class="cdx-search-input cdx-search-input--has-end-button">\n\t\t\t\t<div id="simpleSearch" class="cdx-search-input__input-wrapper"  data-search-loc="header-moved">\n\t\t\t\t\t<div class="cdx-text-input cdx-text-input--has-start-icon">\n\t\t\t\t\t\t<input\n\t\t\t\t\t\t\tclass="cdx-text-input__input"\n\t\t\t\t\t\t\t type="search" name="search" placeholder="Search Wikipedia" aria-label="Search Wikipedia" autocapitalize="sentences" title="Search Wikipedia [f]" accesskey="f" id="searchInput"\n\t\t\t\t\t\t\t>\n\t\t\t\t\t\t<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>\n\t\t\t\t\t</div>\n\t\t\t\t\t<input type="hidden" name="title" value="Special:Search">\n\t\t\t\t</div>\n\t\t\t\t<button class="cdx-button cdx-search-input__end-button">Search</button>\n\t\t\t</form>\n\t\t</div>\n\t</div>\n</div>\n\n\t\t\t<nav class="vector-user-links vector-user-links-wide" aria-label="Personal tools">\n\t<div class="vector-user-links-main">\n\t\n<div id="p-vector-user-menu-preferences" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n<div id="p-vector-user-menu-userpage" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t<nav class="vector-appearance-landmark" aria-label="Appearance">\n\t\t\n<div id="vector-appearance-dropdown" class="vector-dropdown "  title="Change the appearance of the page&#039;s font size, width, and color" >\n\t<input type="checkbox" id="vector-appearance-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-appearance-dropdown" class="vector-dropdown-checkbox "  aria-label="Appearance"  >\n\t<label id="vector-appearance-dropdown-label" for="vector-appearance-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>\n\n<span class="vector-dropdown-label-text">Appearance</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\t<div id="vector-appearance-unpinned-container" class="vector-unpinned-container">\n\t\t\t\t\n\t\t\t</div>\n\t\t\n\t</div>\n</div>\n\n\t</nav>\n\t\n<div id="p-vector-user-menu-notifications" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n<div id="p-vector-user-menu-overflow" class="vector-menu mw-portlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t<li id="pt-sitesupport-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw="interface" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en" class=""><span>Donate</span></a>\n</li>\n<li id="pt-createaccount-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw="interface" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+universities" title="You are encouraged to create an account and log in; however, it is not mandatory" class=""><span>Create account</span></a>\n</li>\n<li id="pt-login-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw="interface" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+universities" title="You&#039;re encouraged to log in; however, it&#039;s not mandatory. [o]" accesskey="o" class=""><span>Log in</span></a>\n</li>\n\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t</div>\n\t\n<div id="vector-user-links-dropdown" class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out"  title="Log in and more options" >\n\t<input type="checkbox" id="vector-user-links-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-user-links-dropdown" class="vector-dropdown-checkbox "  aria-label="Personal tools"  >\n\t<label id="vector-user-links-dropdown-label" for="vector-user-links-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>\n\n<span class="vector-dropdown-label-text">Personal tools</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\n<div id="p-personal" class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item"  title="User menu" >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t<li id="pt-sitesupport" class="user-links-collapsible-item mw-list-item"><a href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a></li><li id="pt-createaccount" class="user-links-collapsible-item mw-list-item"><a href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+universities" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a></li><li id="pt-login" class="user-links-collapsible-item mw-list-item"><a href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+universities" title="You&#039;re encouraged to log in; however, it&#039;s not mandatory. [o]" accesskey="o"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Log in</span></a></li>\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n<div id="p-user-menu-anon-editor" class="vector-menu mw-portlet mw-portlet-user-menu-anon-editor"  >\n\t<div class="vector-menu-heading">\n\t\tPages for logged out editors <a href="/wiki/Help:Introduction" aria-label="Learn more about editing"><span>learn more</span></a>\n\t</div>\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t<li id="pt-anoncontribs" class="mw-list-item"><a href="/wiki/Special:MyContributions" title="A list of edits made from this IP

In [60]:
soup = BeautifulSoup(response.content)
soup

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>List of largest universities - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"17eedded-6bbe-41df-89d4-185f1a2ff066","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_universities","wgTitle":"List of largest universities","wgCurRevisionId":1276835439,"wgRevisionId":1276835439,"wgArticleId":41435822,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["CS1 Japanese-language sources (ja)","CS1 Lithuanian-language sources (lt)","Articles with short description","Short description is different from Wikidata","Articles needing additional references from January 2015","All articles needing additional references","Lists of universities and colleges by country","Lists of education-related superlatives"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_universities","wgRelevantArticleId":41435822,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgCiteReferencePreviewsActive":false,"wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":20000,"wgEditSubmitButtonLabelPublish":true,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q17098461","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","ext.wikimediamessages.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.tablesorter","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","ext.checkUser.clientHints","ext.quicksurveys.init","ext.growthExperiments.SuggestedEditSession"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.44.0-wmf.23" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="width=1120" name="viewport"/>
<meta content="List of largest universities - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="//en.m.wikipedia.org/wiki/List_of_largest_universities" media="only screen and (max-width: 640px)" rel="alternate"/>
<link href="/w/index.php?title=List_of_largest_universities&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/List_of_largest_universities" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch"/>
<link href="auth.wikimedia.org" rel="dns-prefetch"/>
</head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_universities rootpage-List_of_largest_universities skin-vector-2022 action-view"><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a href="/wiki/Special:SpecialPages"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/wikipedia.png" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="13" src="/static/images/mobile/copyright/wikipedia-tagline-en.svg" style="width: 7.3125em; height: 0.8125em;" width="117"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="sentences" class="cdx-text-input__input" id="searchInput" name="search" placeholder="Search Wikipedia" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-sitesupport-2"><a class="" data-mw="interface" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2"><a class="" data-mw="interface" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+universities" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-login-2"><a accesskey="o" class="" data-mw="interface" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+universities" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item" id="pt-sitesupport"><a href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-createaccount"><a href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+universities" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-login"><a accesskey="o" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+universities" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Log in</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-user-menu-anon-editor" id="p-user-menu-anon-editor">
<div class="vector-menu-heading">
		Pages for logged out editors <a aria-label="Learn more about editing" href="/wiki/Help:Introduction"><span>learn more</span></a>
</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="pt-anoncontribs"><a accesskey="y" href="/wiki/Special:MyContributions" title="A list of edits made from this IP address [y]"><span>Contributions</span></a></li><li class="mw-list-item" id="pt-anontalk"><a accesskey="n" href="/wiki/Special:MyTalk" title="Discussion about edits from this IP address [n]"><span>Talk</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</nav>
</div>
</header>
</div>
<div class="mw-page-container">
<div class="mw-page-container-inner">
<div class="vector-sitenotice-container">
<div id="siteNotice"><!-- CentralNotice --></div>
</div>
<div class="vector-column-start">
<div class="vector-main-menu-container">
<div id="mw-navigation">
<nav aria-label="Site" class="vector-main-menu-landmark" id="mw-panel">
<div class="vector-pinned-container" id="vector-main-menu-pinned-container">
</div>
</nav>
</div>
</div>
<div class="vector-sticky-pinned-container">
<nav aria-label="Contents" class="mw-table-of-contents-container vector-toc-landmark" data-event-name="ui.sidebar-toc" id="mw-panel-toc">

In [62]:
table = soup.find('table', attrs ={'class': 'sortable'})

In [64]:
table

<table class="sortable wikitable">
<tbody><tr>
<th>Country
</th>
<th>University
</th>
<th>Founded
</th>
<th>Type
</th>
<th>Enrollment
</th>
<th>Ref
</th></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="500" data-file-width="700" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/40px-Flag_of_Albania.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/60px-Flag_of_Albania.svg.png 2x" width="21"/></span></span> </span><a href="/wiki/Albania" title="Albania">Albania</a>
</td>
<td><a href="/wiki/University_of_Tirana" title="University of Tirana">University of Tirana</a>
</td>
<td style="text-align: right;">1957
</td>
<td>Public
</td>
<td style="text-align: right;">35,000
</td>
<td>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/40px-Flag_of_Algeria.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/60px-Flag_of_Algeria.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Algeria" title="Algeria">Algeria</a>
</td>
<td><a href="/wiki/List_of_universities_in_Algeria" title="List of universities in Algeria">Constantine University</a>
</td>
<td style="text-align: right;">1978
</td>
<td>Public
</td>
<td style="text-align: right;">85,000
</td>
<td>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/23px-Flag_of_Angola.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/35px-Flag_of_Angola.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/45px-Flag_of_Angola.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Angola" title="Angola">Angola</a>
</td>
<td><a href="/wiki/Agostinho_Neto_University" title="Agostinho Neto University">Agostinho Neto University</a>
</td>
<td style="text-align: right;">1962
</td>
<td>Public
</td>
<td style="text-align: right;">29,827
</td>
<td>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="500" data-file-width="800" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/23px-Flag_of_Argentina.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/35px-Flag_of_Argentina.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/46px-Flag_of_Argentina.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Argentina" title="Argentina">Argentina</a>
</td>
<td><a href="/wiki/University_of_Buenos_Aires" title="University of Buenos Aires">University of Buenos Aires</a>
</td>
<td style="text-align: right;">1821
</td>
<td>Public
</td>
<td style="text-align: right;">311,175
</td>
<td>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="640" data-file-width="1280" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/40px-Flag_of_Australia_%28converted%29.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/60px-Flag_of_Australia_%28converted%29.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Australia" title="Australia">Australia</a>
</td>
<td><a href="/wiki/Monash_University" title="Monash University">Monash University</a>
</td>
<td style="text-align: right;">1958
</td>
<td>Public
</td>
<td style="text-align: right;">73,807
</td>
<td><sup class="reference" id="cite_ref-1"><a href="#cite_note-1"><span class="cite-bracket">[</span>1<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/23px-Flag_of_Austria.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/35px-Flag_of_Austria.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/45px-Flag_of_Austria.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Austria" title="Austria">Austria</a>
</td>
<td><a href="/wiki/University_of_Vienna" title="University of Vienna">University of Vienna</a>
</td>
<td style="text-align: right;">1365
</td>
<td>Public
</td>
<td style="text-align: right;">91,000
</td>
<td><sup class="reference" id="cite_ref-univie_2-0"><a href="#cite_note-univie-2"><span class="cite-bracket">[</span>2<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="307" data-file-width="512" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/23px-Flag_of_Bangladesh.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/35px-Flag_of_Bangladesh.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/46px-Flag_of_Bangladesh.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Bangladesh" title="Bangladesh">Bangladesh</a>
</td>
<td><a href="/wiki/National_University,_Bangladesh" title="National University, Bangladesh">National University, Bangladesh</a>
</td>
<td style="text-align: right;">1992
</td>
<td>Public
</td>
<td style="text-align: right;">2,097,182
</td>
<td>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="1200" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/40px-Flag_of_Belarus.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/60px-Flag_of_Belarus.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Belarus" title="Belarus">Belarus</a>
</td>
<td><a href="/wiki/Belarusian_State_University" title="Belarusian State University">Belarusian State University</a>
</td>
<td style="text-align: right;">1921
</td>
<td>Public
</td>
<td style="text-align: right;">25,500
</td>
<td><sup class="reference" id="cite_ref-3"><a href="#cite_note-3"><span class="cite-bracket">[</span>3<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/40px-Flag_of_Belgium_%28civil%29.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/60px-Flag_of_Belgium_%28civil%29.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Belgium" title="Belgium">Belgium</a>
</td>
<td><a class="mw-redirect" href="/wiki/Katholieke_Universiteit_Leuven" title="Katholieke Universiteit Leuven">KU Leuven</a>
</td>
<td style="text-align: right;">1425
</td>
<td>Private, state-funded
</td>
<td style="text-align: right;">55,484
</td>
<td>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="400" data-file-width="800" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/40px-Flag_of_Bosnia_and_Herzegovina.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/60px-Flag_of_Bosnia_and_Herzegovina.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Bosnia_and_Herzegovina" title="Bosnia and Herzegovina">Bosnia and Herzegovina</a>
</td>
<td><a href="/wiki/University_of_Sarajevo" title="University of Sarajevo">University of Sarajevo</a>
</td>
<td style="text-align: right;">1949
</td>
<td>Public
</td>
<td style="text-align: right;">30,866
</td>
<td><sup class="reference" id="cite_ref-4"><a href="#cite_note-4"><span class="cite-bracket">[</span>4<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="800" data-file-width="1200" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/40px-Flag_of_Botswana.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/60px-Flag_of_Botswana.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Botswana" title="Botswana">Botswana</a>
</td>
<td><a href="/wiki/University_of_Botswana" title="University of Botswana">University of Botswana</a>
</td>
<td style="text-align: right;">1982
</td>
<td>Public
</td>
<td style="text-align: right;">32,000
</td>
<td>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="700" data-file-width="1000" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/40px-Flag_of_Brazil.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/60px-Flag_of_Brazil.svg.png 2x" width="22"/></span></span> </span><a href="/wiki/Brazil" title="Brazil">Brazil</a>
</td>
<td><a href="/wiki/Est%C3%A1cio_de_S%C3%A1_University" title="Estácio de Sá University">Estácio de Sá University</a>
</td>
<td style="text-align: right;">1970
</td>
<td>Private
</td>
<td style="text-align: right;">215,000
</td>
<td>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="1000" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/23px-Flag_of_Bulgaria.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/35px-Flag_of_Bulgaria.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/46px-Flag_of_Bulgaria.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Bulgaria" title="Bulgaria">Bulgaria</a>
</td>
<td><a href="/wiki/Sofia_University" title="Sofia University">Sofia University</a>
</td>
<td style="text-align: right;">1888
</td>
<td>Public
</td>
<td style="text-align: right;">18 911
</td>
<td>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="1200" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/23px-Flag_of_Canada_%28Pantone%29.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/35px-Flag_of_Canada_%28Pantone%29.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/46px-Flag_of_Canada_%28Pantone%29.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Canada" title="Canada">Canada</a>
</td>
<td><a href="/wiki/University_of_Toronto" title="University of Toronto">University of Toronto</a>
</td>
<td style="text-align: right;">1827
</td>
<td>Public
</td>
<td style="text-align: right;">84,000
</td>
<td>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/China" title="China">China</a>
</td>
<td><a href="/wiki/Shanghai_Open_University" title="Shanghai Open University">Shanghai Open University</a>
</td>
<td style="text-align: right;">1960
</td>
<td>Public
</td>
<td style="text-align: right;">80,000
</td>
<td>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/40px-Flag_of_Colombia.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/60px-Flag_of_Colombia.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Colombia" title="Colombia">Colombia</a>
</td>
<td><a href="/wiki/National_University_of_Colombia" title="National University of Colombia">National University of Colombia</a>
</td>
<td style="text-align: right;">1867
</td>
<td>Public
</td>
<td style="text-align: right;">53,581
</td>
<td><sup class="reference" id="cite_ref-5"><a href="#cite_note-5"><span class="cite-bracket">[</span>5<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="1000" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Costa_Rica.svg/40px-Flag_of_Costa_Rica.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Costa_Rica.svg/60px-Flag_of_Costa_Rica.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Costa_Rica" title="Costa Rica">Costa Rica</a>
</td>
<td><a class="mw-redirect" href="/wiki/Universidad_de_Costa_Rica" title="Universidad de Costa Rica">Universidad de Costa Rica</a>
</td>
<td style="text-align: right;">1940
</td>
<td>Public
</td>
<td style="text-align: right;">42,750
</td>
<td><sup class="reference" id="cite_ref-6"><a href="#cite_note-6"><span class="cite-bracket">[</span>6<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span typeof="mw:File/Frameless"><a class="mw-file-description" href="/wiki/File:Flag_of_Croatia_at_the_UN.svg"><img class="mw-file-element" data-file-height="600" data-file-width="1000" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/58/Flag_of_Croatia_at_the_UN.svg/40px-Flag_of_Croatia_at_the_UN.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/58/Flag_of_Croatia_at_the_UN.svg/60px-Flag_of_Croatia_at_the_UN.svg.png 2x" width="25"/></a></span> <a href="/wiki/Croatia" title="Croatia">Croatia</a>
</td>
<td><a href="/wiki/University_of_Zagreb" title="University of Zagreb">University of Zagreb</a>
</td>
<td style="text-align: right;">1669
</td>
<td>Public
</td>
<td style="text-align: right;">72,480
</td>
<td><sup class="reference" id="cite_ref-7"><a href="#cite_note-7"><span class="cite-bracket">[</span>7<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="387" data-file-width="512" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/20px-Flag_of_Denmark.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/31px-Flag_of_Denmark.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/40px-Flag_of_Denmark.svg.png 2x" width="20"/></span></span> </span><a href="/wiki/Denmark" title="Denmark">Denmark</a>
</td>
<td><a href="/wiki/Aarhus_University" title="Aarhus University">Aarhus University</a>
</td>
<td style="text-align: right;">1928
</td>
<td>Public
</td>
<td style="text-align: right;">43,600
</td>
<td>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/40px-Flag_of_the_Dominican_Republic.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/60px-Flag_of_the_Dominican_Republic.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Dominican_Republic" title="Dominican Republic">Dominican Republic</a>
</td>
<td><a href="/wiki/Universidad_Aut%C3%B3noma_de_Santo_Domingo" title="Universidad Autónoma de Santo Domingo">Universidad Autónoma de Santo Domingo</a>
</td>
<td style="text-align: right;">1538
</td>
<td>Public
</td>
<td style="text-align: right;">170,530
</td>
<td>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/23px-Flag_of_Egypt.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/35px-Flag_of_Egypt.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/45px-Flag_of_Egypt.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Egypt" title="Egypt">Egypt</a>
</td>
<td><a href="/wiki/Ain_Shams_University" title="Ain Shams University">Ain Shams University</a>
</td>
<td style="text-align: right;">1950
</td>
<td>Public
</td>
<td style="text-align: right;">170,000
</td>
<td>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="630" data-file-width="990" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/23px-Flag_of_Estonia.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/35px-Flag_of_Estonia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/46px-Flag_of_Estonia.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Estonia" title="Estonia">Estonia</a>
</td>
<td><a href="/wiki/University_of_Tartu" title="University of Tartu">University of Tartu</a>
</td>
<td style="text-align: right;">1632
</td>
<td>Public
</td>
<td style="text-align: right;">14,000
</td>
<td>
</td></tr>
<tr>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="1100" data-file-width="1800" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/40px-Flag_of_Finland.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/60px-Flag_of_Finland.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Finland" title="Finland">Finland</a>
</td>
<td><a href="/wiki/University_of_Helsinki" title="University of Helsinki">University of Helsinki</a>
</td>
<td style="text-align: right;">1640
</td>
<td>Public
</td>
<td style="text-align: right;">36,500
</td>
<td>
</td></tr>
<tr>

In [70]:
trs = table.findAll(('tr'))
trs[0]

<tr>
<th>Country
</th>
<th>University
</th>
<th>Founded
</th>
<th>Type
</th>
<th>Enrollment
</th>
<th>Ref
</th></tr>

In [78]:
trs[0].findAll('th')
columns=[]
for item in trs[0].findAll('th'):
    print(item.text.strip())
    columns.append(item.text.strip())

Country
University
Founded
Type
Enrollment
Ref

In [125]:
columns = list(map( lambda x: x.text.strip(), trs[0].findAll('th')))
columns

['Country', 'University', 'Founded', 'Type', 'Enrollment', 'Ref']

In [88]:
rows = trs[1:]

In [111]:
rows[0].findAll('td')

[<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="500" data-file-width="700" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/40px-Flag_of_Albania.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/60px-Flag_of_Albania.svg.png 2x" width="21"/></span></span> </span><a href="/wiki/Albania" title="Albania">Albania</a>
 </td>,
 <td><a href="/wiki/University_of_Tirana" title="University of Tirana">University of Tirana</a>
 </td>,
 <td style="text-align: right;">1957
 </td>,
 <td>Public
 </td>,
 <td style="text-align: right;">35,000
 </td>,
 <td>
 </td>]

In [117]:
list(map(lambda x: x.text.strip(), rows[0].findAll('td')))

['Albania', 'University of Tirana', '1957', 'Public', '35,000', '']

In [129]:
columns[-1] = 'Links'
columns

['Country', 'University', 'Founded', 'Type', 'Enrollment', 'Links']

In [147]:
def extract_rows(tr):
    row_soup_list = tr.findAll('td')
    row = list(map(lambda x: x.text.strip(), row_soup_list))
    link =  row_soup_list[1].a.attrs['href'].lstrip('/')
    row[-1] = f' https://en.wikipedia.org/{link}' if link else ' '
    #print('link:', link)
    return row

In [141]:
extract_rows(rows[0])

link: wiki/University_of_Tirana

['Albania',
 'University of Tirana',
 '1957',
 'Public',
 '35,000',
 ' https://en.wikipedia.org/wiki/University_of_Tirana']

In [131]:
rows[0].findAll('td')[1]

<td><a href="/wiki/University_of_Tirana" title="University of Tirana">University of Tirana</a>
</td>

In [107]:
rows[0].findAll('td')[1].a.attrs['href']

'/wiki/University_of_Tirana'

In [151]:
data = list(map(extract_rows, rows))
data

[['Albania',
  'University of Tirana',
  '1957',
  'Public',
  '35,000',
  ' https://en.wikipedia.org/wiki/University_of_Tirana'],
 ['Algeria',
  'Constantine University',
  '1978',
  'Public',
  '85,000',
  ' https://en.wikipedia.org/wiki/List_of_universities_in_Algeria'],
 ['Angola',
  'Agostinho Neto University',
  '1962',
  'Public',
  '29,827',
  ' https://en.wikipedia.org/wiki/Agostinho_Neto_University'],
 ['Argentina',
  'University of Buenos Aires',
  '1821',
  'Public',
  '311,175',
  ' https://en.wikipedia.org/wiki/University_of_Buenos_Aires'],
 ['Australia',
  'Monash University',
  '1958',
  'Public',
  '73,807',
  ' https://en.wikipedia.org/wiki/Monash_University'],
 ['Austria',
  'University of Vienna',
  '1365',
  'Public',
  '91,000',
  ' https://en.wikipedia.org/wiki/University_of_Vienna'],
 ['Bangladesh',
  'National University, Bangladesh',
  '1992',
  'Public',
  '2,097,182',
  ' https://en.wikipedia.org/wiki/National_University,_Bangladesh'],
 ['Belarus',
  'Belarusian State University',
  '1921',
  'Public',
  '25,500',
  ' https://en.wikipedia.org/wiki/Belarusian_State_University'],
 ['Belgium',
  'KU Leuven',
  '1425',
  'Private, state-funded',
  '55,484',
  ' https://en.wikipedia.org/wiki/Katholieke_Universiteit_Leuven'],
 ['Bosnia and Herzegovina',
  'University of Sarajevo',
  '1949',
  'Public',
  '30,866',
  ' https://en.wikipedia.org/wiki/University_of_Sarajevo'],
 ['Botswana',
  'University of Botswana',
  '1982',
  'Public',
  '32,000',
  ' https://en.wikipedia.org/wiki/University_of_Botswana'],
 ['Brazil',
  'Estácio de Sá University',
  '1970',
  'Private',
  '215,000',
  ' https://en.wikipedia.org/wiki/Est%C3%A1cio_de_S%C3%A1_University'],
 ['Bulgaria',
  'Sofia University',
  '1888',
  'Public',
  '18 911',
  ' https://en.wikipedia.org/wiki/Sofia_University'],
 ['Canada',
  'University of Toronto',
  '1827',
  'Public',
  '84,000',
  ' https://en.wikipedia.org/wiki/University_of_Toronto'],
 ['China',
  'Shanghai Open University',
  '1960',
  'Public',
  '80,000',
  ' https://en.wikipedia.org/wiki/Shanghai_Open_University'],
 ['Colombia',
  'National University of Colombia',
  '1867',
  'Public',
  '53,581',
  ' https://en.wikipedia.org/wiki/National_University_of_Colombia'],
 ['Costa Rica',
  'Universidad de Costa Rica',
  '1940',
  'Public',
  '42,750',
  ' https://en.wikipedia.org/wiki/Universidad_de_Costa_Rica'],
 ['Croatia',
  'University of Zagreb',
  '1669',
  'Public',
  '72,480',
  ' https://en.wikipedia.org/wiki/University_of_Zagreb'],
 ['Denmark',
  'Aarhus University',
  '1928',
  'Public',
  '43,600',
  ' https://en.wikipedia.org/wiki/Aarhus_University'],
 ['Dominican Republic',
  'Universidad Autónoma de Santo Domingo',
  '1538',
  'Public',
  '170,530',
  ' https://en.wikipedia.org/wiki/Universidad_Aut%C3%B3noma_de_Santo_Domingo'],
 ['Egypt',
  'Ain Shams University',
  '1950',
  'Public',
  '170,000',
  ' https://en.wikipedia.org/wiki/Ain_Shams_University'],
 ['Estonia',
  'University of Tartu',
  '1632',
  'Public',
  '14,000',
  ' https://en.wikipedia.org/wiki/University_of_Tartu'],
 ['Finland',
  'University of Helsinki',
  '1640',
  'Public',
  '36,500',
  ' https://en.wikipedia.org/wiki/University_of_Helsinki'],
 ['France',
  "Centre national d'enseignement à distance",
  '1939',
  'Public',
  ' https://en.wikipedia.org/wiki/Centre_national_d%27enseignement_%C3%A0_distance'],
 ['Germany',
  'IU International University of Applied Sciences',
  '1998',
  'Private',
  '130,000',
  ' https://en.wikipedia.org/wiki/IU_International_University_of_Applied_Sciences'],
 ['Greece',
  'National and Kapodistrian University of Athens',
  '1837',
  'Public',
  '104,000',
  ' https://en.wikipedia.org/wiki/National_and_Kapodistrian_University_of_Athens'],
 ['Guatemala',
  'Universidad de San Carlos de Guatemala',
  '1676',
  'Public',
  '124,000',
  ' https://en.wikipedia.org/wiki/Universidad_de_San_Carlos_de_Guatemala'],
 ['Hong Kong',
  'Hong Kong Polytechnic University',
  '1937',
  'Public',
  '32,000',
  ' https://en.wikipedia.org/wiki/Hong_Kong_Polytechnic_University'],
 ['Iceland',
  'University of Iceland',
  '1911',
  'Public',
  '13,782',
  ' https://en.wikipedia.org/wiki/University_of_Iceland'],
 ['India',
  'Indira Gandhi National Open University',
  '1985',
  'Public',
  '7,140,000',
  ' https://en.wikipedia.org/wiki/Indira_Gandhi_National_Open_University'],
 ['Indonesia',
  'Universitas Terbuka',
  '1984',
  'Public',
  '1,045,665 (total) as per 2019/2020[14]\n311,028 (active) as per 4 November 2020 [15]',
  ' https://en.wikipedia.org/wiki/Universitas_Terbuka'],
 ['Iran',
  'Islamic Azad University',
  '1982',
  'Semi-private',
  '1,000,000',
  ' https://en.wikipedia.org/wiki/Islamic_Azad_University'],
 ['Ireland',
  'University College Dublin',
  '1834',
  'Public (formerly private)',
  '32,900',
  ' https://en.wikipedia.org/wiki/University_College_Dublin'],
 ['Israel',
  'Tel Aviv University',
  '1956',
  'Public',
  '26,023',
  ' https://en.wikipedia.org/wiki/Tel_Aviv_University'],
 ['Italy',
  'Sapienza University of Rome',
  '1303',
  'Public',
  '112,564',
  ' https://en.wikipedia.org/wiki/Sapienza_University_of_Rome'],
 ['Japan',
  'Nihon University',
  '1889',
  'Private',
  '70,667',
  ' https://en.wikipedia.org/wiki/Nihon_University'],
 ['Kenya',
  'University of Nairobi',
  '1970',
  'Public',
  '84,000',
  ' https://en.wikipedia.org/wiki/University_of_Nairobi'],
 ['Kosovo',
  'Universiteti i Prishtinës',
  '1999',
  'Public',
  '41,833',
  ' https://en.wikipedia.org/wiki/Universiteti_i_Prishtin%C3%ABs'],
 ['Lithuania',
  'Vilnius University',
  '1579',
  'Public',
  '23,606',
  ' https://en.wikipedia.org/wiki/Vilnius_University'],
 ['Macau',
  'Macau University of Science and Technology',
  '2000',
  'Private',
  '10,373',
  ' https://en.wikipedia.org/wiki/Macau_University_of_Science_and_Technology'],
 ['Malaysia',
  'Universiti Teknologi MARA',
  '1956',
  'Public',
  '100,000',
  ' https://en.wikipedia.org/wiki/Universiti_Teknologi_MARA'],
 ['Mexico',
  'National Autonomous University of Mexico',
  '1910',
  'Public',
  '349,515',
  ' https://en.wikipedia.org/wiki/National_Autonomous_University_of_Mexico'],
 ['Nepal',
  'Tribhuvan University',
  '1959',
  'Public',
  '604,437',
  ' https://en.wikipedia.org/wiki/Tribhuvan_University'],
 ['Netherlands',
  'Utrecht University',
  '1636',
  'Public',
  '39,769',
  ' https://en.wikipedia.org/wiki/Utrecht_University'],
 ['New Zealand',
  'University of Auckland',
  '1883',
  'Public',
  '33,050',
  ' https://en.wikipedia.org/wiki/University_of_Auckland'],
 ['North Macedonia',
  'University of Skopje',
  '1943',
  'Public',
  '50,000',
  ' https://en.wikipedia.org/wiki/University_of_Skopje'],
 ['Norway',
  'Norwegian University of Science and Technology',
  '1996',
  'Public',
  '39,000',
  ' https://en.wikipedia.org/wiki/Norwegian_University_of_Science_and_Technology'],
 ['Pakistan',
  'Virtual University of Pakistan',
  '2002',
  'Public',
  '165,000',
  ' https://en.wikipedia.org/wiki/Virtual_University_of_Pakistan'],
 ['Peru',
  'National University of San Marcos',
  '1551',
  'Private',
  '37,032',
  ' https://en.wikipedia.org/wiki/National_University_of_San_Marcos'],
 ['Philippines',
  'Polytechnic University of the Philippines',
  '1904',
  'Public',
  '68,249',
  ' https://en.wikipedia.org/wiki/Polytechnic_University_of_the_Philippines'],
 ['Poland',
  'University of Warsaw',
  '1816',
  'Public',
  '44,400',
  ' https://en.wikipedia.org/wiki/University_of_Warsaw'],
 ['Portugal',
  'University of Lisbon',
  '1288',
  'Public',
  '48,100',
  ' https://en.wikipedia.org/wiki/University_of_Lisbon'],
 ['Romania',
  'Spiru Haret University',
  '1991',
  'Private',
  '311,928',
  ' https://en.wikipedia.org/wiki/Spiru_Haret_University'],
 ['Russia',
  'Modern University for the Humanities',
  '1992',
  'Private',
  '200,000',
  ' https://en.wikipedia.org/wiki/Modern_University_for_the_Humanities'],
 ['Saudi Arabia',
  'King Abdulaziz University',
  '1976',
  'Public',
  '177,234',
  ' https://en.wikipedia.org/wiki/King_Abdulaziz_University'],
 ['Singapore',
  'National University of Singapore',
  '1905',
  'Public',
  '38,300',
  ' https://en.wikipedia.org/wiki/National_University_of_Singapore'],
 ['Slovenia',
  'University of Ljubljana',
  '1919',
  'Public',
  '48,821',
  ' https://en.wikipedia.org/wiki/University_of_Ljubljana'],
 ['South Africa',
  'University of South Africa',
  '1873',
  'Public',
  '328,179',
  ' https://en.wikipedia.org/wiki/University_of_South_Africa'],
 ['South Korea',
  'Korea National Open University',
  '1972',
  'Public',
  '173,758',
  ' https://en.wikipedia.org/wiki/Korea_National_Open_University'],
 ['Spain',
  'National University of Distance Education',
  '1972',
  'Public',
  '260,079',
  ' https://en.wikipedia.org/wiki/National_University_of_Distance_Education'],
 ['Sweden',
  'Lund University',
  '1666',
  'Public',
  '30,646',
  ' https://en.wikipedia.org/wiki/Lund_University'],
 ['Switzerland',
  'University of Zurich',
  '1833[34]',
  'Public',
  '26,356',
  ' https://en.wikipedia.org/wiki/University_of_Zurich'],
 ['Taiwan',
  'National Taiwan University',
  '1928',
  'Public',
  '31,758',
  ' https://en.wikipedia.org/wiki/National_Taiwan_University'],
 ['Thailand',
  'Ramkhamhaeng University',
  '1971',
  'Public',
  '525,000',
  ' https://en.wikipedia.org/wiki/Ramkhamhaeng_University'],
 ['Trinidad and Tobago',
  'University of the West Indies',
  '1960',
  'Public',
  '60,000+',
  ' https://en.wikipedia.org/wiki/University_of_the_West_Indies'],
 ['Turkey',
  'Anadolu University',
  '1958',
  'Public',
  '1,969,733',
  ' https://en.wikipedia.org/wiki/Anadolu_University'],
 ['United Kingdom',
  'Open University',
  '1969',
  'Public',
  '253,075',
  ' https://en.wikipedia.org/wiki/Open_University'],
 ['United States',
  'Texas A&M University',
  '1876',
  'Public',
  '73,284',
  ' https://en.wikipedia.org/wiki/Texas_A%26M_University'],
 ['Uruguay',
  'University of the Republic',
  '1949',
  'Public',
  '144,108',
  ' https://en.wikipedia.org/wiki/University_of_the_Republic'],
 ['Venezuela',
  'Universidad Central de Venezuela',
  '1721',
  'Public',
  '41,059',
  ' https://en.wikipedia.org/wiki/Universidad_Central_de_Venezuela']]

In [155]:
df = pd.DataFrame(data= data, columns = columns)
df

,Country,University,Founded,Type,Enrollment,Links
0,Albania,University of Tirana,1957,Public,"35,000",https://en.wikipedia.org/wiki/University_of_T...
1,Algeria,Constantine University,1978,Public,"85,000",https://en.wikipedia.org/wiki/List_of_univers...
2,Angola,Agostinho Neto University,1962,Public,"29,827",https://en.wikipedia.org/wiki/Agostinho_Neto_...
3,Argentina,University of Buenos Aires,1821,Public,"311,175",https://en.wikipedia.org/wiki/University_of_B...
4,Australia,Monash University,1958,Public,"73,807",https://en.wikipedia.org/wiki/Monash_University
...,...,...,...,...,...,...
65,Turkey,Anadolu University,1958,Public,"1,969,733",https://en.wikipedia.org/wiki/Anadolu_University
66,United Kingdom,Open University,1969,Public,"253,075",https://en.wikipedia.org/wiki/Open_University
67,United States,Texas A&M University,1876,Public,"73,284",https://en.wikipedia.org/wiki/Texas_A%26M_Uni...
68,Uruguay,University of the Republic,1949,Public,"144,108",https://en.wikipedia.org/wiki/University_of_t...
69,Venezuela,Universidad Central de Venezuela,1721,Public,"41,059",https://en.wikipedia.org/wiki/Universidad_Cen...

In [146]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

uri = 'https://en.wikipedia.org/wiki/List_of_largest_universities_and_university_networks_by_enrollment'

my_respon = requests.get(uri)
my_respon.content

b'<!DOCTYPE html>\n<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available" lang="en" dir="ltr">\n<head>\n<meta charset="UTF-8">\n<title>List of largest universities and university networks by enrollment - Wikipedia</title>\n<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split(\'%2C\').forEach(function(pref){className=className.replace(new RegExp(\'(^| )\'+pref.replace(/-clientpref-\\w+$|[^\\w-]+/g,\'\')+\'-clientpref-\\\\w+( |$)\'),\'$1\'+pref+\'$2\');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"75ac2d20-f5e4-4674-9412-21bf78f91914","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_universities_and_university_networks_by_enrollment","wgTitle":"List of largest universities and university networks by enrollment","wgCurRevisionId":1279979577,"wgRevisionId":1279979577,"wgArticleId":5205784,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["All articles with bare URLs for citations","Articles with bare URLs for citations from August 2024","Webarchive template wayback links","CS1 errors: missing title","CS1 errors: bare URL","All articles with dead external links","Articles with dead external links from September 2017","Articles with permanently dead external links","CS1 Spanish-language sources (es)","CS1 Italian-language sources (it)","CS1 French-language sources (fr)","Articles with short description","Short description is different from Wikidata","Use dmy dates from February 2021","All articles with unsourced statements","Articles with unsourced statements from May 2018","World records","Lists of universities and colleges by enrollment"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_universities_and_university_networks_by_enrollment","wgRelevantArticleId":5205784,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgCiteReferencePreviewsActive":false,"wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":40000,"wgEditSubmitButtonLabelPublish":true,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q6139054","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false};\nRLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","ext.wikimediamessages.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.tablesorter","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","ext.checkUser.clientHints","ext.quicksurveys.init","ext.growthExperiments.SuggestedEditSession"];</script>\n<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\\\","watchToken":"+\\\\","csrfToken":"+\\\\"});\n}];});});</script>\n<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022">\n<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>\n<meta name="ResourceLoaderDynamicStyles" content="">\n<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022">\n<meta name="generator" content="MediaWiki 1.44.0-wmf.22">\n<meta name="referrer" content="origin">\n<meta name="referrer" content="origin-when-cross-origin">\n<meta name="robots" content="max-image-preview:standard">\n<meta name="format-detection" content="telephone=no">\n<meta name="viewport" content="width=1120">\n<meta property="og:title" content="List of largest universities and university networks by enrollment - Wikipedia">\n<meta property="og:type" content="website">\n<link rel="preconnect" href="//upload.wikimedia.org">\n<link rel="alternate" media="only screen and (max-width: 640px)" href="//en.m.wikipedia.org/wiki/List_of_largest_universities_and_university_networks_by_enrollment">\n<link rel="alternate" type="application/x-wiki" title="Edit this page" href="/w/index.php?title=List_of_largest_universities_and_university_networks_by_enrollment&amp;action=edit">\n<link rel="apple-touch-icon" href="/static/apple-touch/wikipedia.png">\n<link rel="icon" href="/static/favicon/wikipedia.ico">\n<link rel="search" type="application/opensearchdescription+xml" href="/w/rest.php/v1/search" title="Wikipedia (en)">\n<link rel="EditURI" type="application/rsd+xml" href="//en.wikipedia.org/w/api.php?action=rsd">\n<link rel="canonical" href="https://en.wikipedia.org/wiki/List_of_largest_universities_and_university_networks_by_enrollment">\n<link rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">\n<link rel="alternate" type="application/atom+xml" title="Wikipedia Atom feed" href="/w/index.php?title=Special:RecentChanges&amp;feed=atom">\n<link rel="dns-prefetch" href="//meta.wikimedia.org" />\n<link rel="dns-prefetch" href="login.wikimedia.org">\n</head>\n<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_universities_and_university_networks_by_enrollment rootpage-List_of_largest_universities_and_university_networks_by_enrollment skin-vector-2022 action-view"><a class="mw-jump-link" href="#bodyContent">Jump to content</a>\n<div class="vector-header-container">\n\t<header class="vector-header mw-header">\n\t\t<div class="vector-header-start">\n\t\t\t<nav class="vector-main-menu-landmark" aria-label="Site">\n\t\t\t\t\n<div id="vector-main-menu-dropdown" class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right"  title="Main menu" >\n\t<input type="checkbox" id="vector-main-menu-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-main-menu-dropdown" class="vector-dropdown-checkbox "  aria-label="Main menu"  >\n\t<label id="vector-main-menu-dropdown-label" for="vector-main-menu-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>\n\n<span class="vector-dropdown-label-text">Main menu</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\t\t<div id="vector-main-menu-unpinned-container" class="vector-unpinned-container">\n\t\t\n<div id="vector-main-menu" class="vector-main-menu vector-pinnable-element">\n\t<div\n\tclass="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned"\n\tdata-feature-name="main-menu-pinned"\n\tdata-pinnable-element-id="vector-main-menu"\n\tdata-pinned-container-id="vector-main-menu-pinned-container"\n\tdata-unpinned-container-id="vector-main-menu-unpinned-container"\n>\n\t<div class="vector-pinnable-header-label">Main menu</div>\n\t<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>\n\t<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>\n</div>\n\n\t\n<div id="p-navigation" class="vector-menu mw-portlet mw-portlet-navigation"  >\n\t<div class="vector-menu-heading">\n\t\tNavigation\n\t</div>\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t<li id="n-mainpage-description" class="mw-list-item"><a href="/wiki/Main_Page" title="Visit the main page [z]" accesskey="z"><span>Main page</span></a></li><li id="n-contents" class="mw-list-item"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li id="n-currentevents" class="mw-list-item"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li id="n-randompage" class="mw-list-item"><a href="/wiki/Special:Random" title="Visit a randomly selected article [x]" accesskey="x"><span>Random article</span></a></li><li id="n-aboutsite" class="mw-list-item"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li id="n-contactpage" class="mw-list-item"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n\t\n<div id="p-interaction" class="vector-menu mw-portlet mw-portlet-interaction"  >\n\t<div class="vector-menu-heading">\n\t\tContribute\n\t</div>\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t<li id="n-help" class="mw-list-item"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li id="n-introduction" class="mw-list-item"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li id="n-portal" class="mw-list-item"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li id="n-recentchanges" class="mw-list-item"><a href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]" accesskey="r"><span>Recent changes</span></a></li><li id="n-upload" class="mw-list-item"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li id="n-specialpages" class="mw-list-item"><a href="/wiki/Special:SpecialPages"><span>Special pages</span></a></li>\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n</div>\n\n\t\t\t\t</div>\n\n\t</div>\n</div>\n\n\t\t</nav>\n\t\t\t\n<a href="/wiki/Main_Page" class="mw-logo">\n\t<img class="mw-logo-icon" src="/static/images/icons/wikipedia.png" alt="" aria-hidden="true" height="50" width="50">\n\t<span class="mw-logo-container skin-invert">\n\t\t<img class="mw-logo-wordmark" alt="Wikipedia" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;">\n\t\t<img class="mw-logo-tagline" alt="The Free Encyclopedia" src="/static/images/mobile/copyright/wikipedia-tagline-en.svg" width="117" height="13" style="width: 7.3125em; height: 0.8125em;">\n\t</span>\n</a>\n\n\t\t</div>\n\t\t<div class="vector-header-end">\n\t\t\t\n<div id="p-search" role="search" class="vector-search-box-vue  vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box">\n\t<a href="/wiki/Special:Search" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" title="Search Wikipedia [f]" accesskey="f"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>\n\n<span>Search</span>\n\t</a>\n\t<div class="vector-typeahead-search-container">\n\t\t<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">\n\t\t\t<form action="/w/index.php" id="searchform" class="cdx-search-input cdx-search-input--has-end-button">\n\t\t\t\t<div id="simpleSearch" class="cdx-search-input__input-wrapper"  data-search-loc="header-moved">\n\t\t\t\t\t<div class="cdx-text-input cdx-text-input--has-start-icon">\n\t\t\t\t\t\t<input\n\t\t\t\t\t\t\tclass="cdx-text-input__input"\n\t\t\t\t\t\t\t type="search" name="search" placeholder="Search Wikipedia" aria-label="Search Wikipedia" autocapitalize="sentences" title="Search Wikipedia [f]" accesskey="f" id="searchInput"\n\t\t\t\t\t\t\t>\n\t\t\t\t\t\t<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>\n\t\t\t\t\t</div>\n\t\t\t\t\t<input type="hidden" name="title" value="Special:Search">\n\t\t\t\t</div>\n\t\t\t\t<button class="cdx-button cdx-search-input__end-button">Search</button>\n\t\t\t</form>\n\t\t</div>\n\t</div>\n</div>\n\n\t\t\t<nav class="vector-user-links vector-user-links-wide" aria-label="Personal tools">\n\t<div class="vector-user-links-main">\n\t\n<div id="p-vector-user-menu-preferences" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n<div id="p-vector-user-menu-userpage" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t<nav class="vector-appearance-landmark" aria-label="Appearance">\n\t\t\n<div id="vector-appearance-dropdown" class="vector-dropdown "  title="Change the appearance of the page&#039;s font size, width, and color" >\n\t<input type="checkbox" id="vector-appearance-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-appearance-dropdown" class="vector-dropdown-checkbox "  aria-label="Appearance"  >\n\t<label id="vector-appearance-dropdown-label" for="vector-appearance-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>\n\n<span class="vector-dropdown-label-text">Appearance</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\t<div id="vector-appearance-unpinned-container" class="vector-unpinned-container">\n\t\t\t\t\n\t\t\t</div>\n\t\t\n\t</div>\n</div>\n\n\t</nav>\n\t\n<div id="p-vector-user-menu-notifications" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n<div id="p-vector-user-menu-overflow" class="vector-menu mw-portlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t<li id="pt-sitesupport-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw="interface" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en" class=""><span>Donate</span></a>\n</li>\n<li id="pt-createaccount-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw="interface" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+universities+and+university+networks+by+enrollment" title="You are encouraged to create an account and log in; however, it is not mandatory" class=""><span>Create account</span></a>\n</li>\n<li id="pt-login-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw="interface" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+universities+and+university+networks+by+enrollment" title="You&#039;re encouraged to log in; however, it&#039;s not mandatory. [o]" accesskey="o" class=""><span>Log in</span></a>\n</li>\n\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t</div>\n\t\n<div id="vector-user-links-dropdown" class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out"  title="Log in and more options" >\n\t<input type="checkbox" id="vector-user-links-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-user-links-dropdown" class="vector-dropdown-checkbox "  aria-label="Personal tools"  >\n\t<label id="vector-user-links-dropdown-label" for="vector-user-links-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>\n\n<span class="vector-dropdown-label-text">Personal tools</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\n<div id="p-personal" class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item"  title="User menu" >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t<li id="pt-sitesupport" class="user-links-collapsible-item mw-list-item"><a href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a></li><li id="pt-createaccount" class="user-links-collapsible-item mw-list-item"><a href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+universities+and+university+networks+by+enrollment" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a></li><li id="pt-login" class="user-links-collapsible-i

In [148]:
soup = BeautifulSoup(my_respon.content)

soup

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>List of largest universities and university networks by enrollment - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"75ac2d20-f5e4-4674-9412-21bf78f91914","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_universities_and_university_networks_by_enrollment","wgTitle":"List of largest universities and university networks by enrollment","wgCurRevisionId":1279979577,"wgRevisionId":1279979577,"wgArticleId":5205784,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["All articles with bare URLs for citations","Articles with bare URLs for citations from August 2024","Webarchive template wayback links","CS1 errors: missing title","CS1 errors: bare URL","All articles with dead external links","Articles with dead external links from September 2017","Articles with permanently dead external links","CS1 Spanish-language sources (es)","CS1 Italian-language sources (it)","CS1 French-language sources (fr)","Articles with short description","Short description is different from Wikidata","Use dmy dates from February 2021","All articles with unsourced statements","Articles with unsourced statements from May 2018","World records","Lists of universities and colleges by enrollment"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_universities_and_university_networks_by_enrollment","wgRelevantArticleId":5205784,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgCiteReferencePreviewsActive":false,"wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":40000,"wgEditSubmitButtonLabelPublish":true,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q6139054","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","ext.wikimediamessages.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.tablesorter","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","ext.checkUser.clientHints","ext.quicksurveys.init","ext.growthExperiments.SuggestedEditSession"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.44.0-wmf.22" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="width=1120" name="viewport"/>
<meta content="List of largest universities and university networks by enrollment - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="//en.m.wikipedia.org/wiki/List_of_largest_universities_and_university_networks_by_enrollment" media="only screen and (max-width: 640px)" rel="alternate"/>
<link href="/w/index.php?title=List_of_largest_universities_and_university_networks_by_enrollment&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/List_of_largest_universities_and_university_networks_by_enrollment" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch"/>
<link href="login.wikimedia.org" rel="dns-prefetch"/>
</head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_universities_and_university_networks_by_enrollment rootpage-List_of_largest_universities_and_university_networks_by_enrollment skin-vector-2022 action-view"><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a href="/wiki/Special:SpecialPages"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/wikipedia.png" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="13" src="/static/images/mobile/copyright/wikipedia-tagline-en.svg" style="width: 7.3125em; height: 0.8125em;" width="117"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="sentences" class="cdx-text-input__input" id="searchInput" name="search" placeholder="Search Wikipedia" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-sitesupport-2"><a class="" data-mw="interface" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2"><a class="" data-mw="interface" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+universities+and+university+networks+by+enrollment" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-login-2"><a accesskey="o" class="" data-mw="interface" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+universities+and+university+networks+by+enrollment" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item" id="pt-sitesupport"><a href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-createaccount"><a href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+universities+and+university+networks+by+enrollment" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-login"><a accesskey="o" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+universities+and+university+networks+by+enrollment" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Log in</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-user-menu-anon-editor" id="p-user-menu-anon-editor">
<div class="vector-menu-heading">
		Pages for logged out editors <a aria-label="Learn more about editing" href="/wiki/Help:Introduction"><span>learn more</span></a>
</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">

In [150]:
table = soup.find('table', attrs ={'class': 'sortable'})

table

<table class="wikitable sortable">
<tbody><tr>
<th>Rank
</th>
<th>Institution
</th>
<th>Location
</th>
<th>Continent
</th>
<th>Founded
</th>
<th>Affiliation
</th>
<th>Distance / In-Person<style data-mw-deduplicate="TemplateStyles:r1041539562">.mw-parser-output .citation{word-wrap:break-word}.mw-parser-output .citation:target{background-color:rgba(0,127,255,0.133)}</style><sup class="citation nobold" id="ref_distancea"><a href="#endnote_distancea">[a]</a></sup>
</th>
<th>Enrollment
</th>
<th class="unsortable">Ref
</th></tr>
<tr>
<td>1
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/India" title="India"><img alt="India" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/35px-Flag_of_India.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/45px-Flag_of_India.svg.png 2x" width="23"/></a></span></span><a href="/wiki/Indira_Gandhi_National_Open_University" title="Indira Gandhi National Open University">Indira Gandhi National Open University</a>
</td>
<td><a href="/wiki/New_Delhi" title="New Delhi">New Delhi</a>, <a href="/wiki/India" title="India">India</a>
</td>
<td>Asia
</td>
<td>1985
</td>
<td>Public
</td>
<td>Distance/In-Person
</td>
<td>7,140,000+
</td>
<td><sup class="reference" id="cite_ref-1"><a href="#cite_note-1"><span class="cite-bracket">[</span>1<span class="cite-bracket">]</span></a></sup>
<p><sup class="reference" id="cite_ref-2"><a href="#cite_note-2"><span class="cite-bracket">[</span>2<span class="cite-bracket">]</span></a></sup><sup class="reference" id="cite_ref-3"><a href="#cite_note-3"><span class="cite-bracket">[</span>3<span class="cite-bracket">]</span></a></sup>
</p>
</td></tr>
<tr>
<td>2
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/Bangladesh" title="Bangladesh"><img alt="Bangladesh" class="mw-file-element" data-file-height="307" data-file-width="512" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/23px-Flag_of_Bangladesh.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/35px-Flag_of_Bangladesh.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/46px-Flag_of_Bangladesh.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/National_University,_Bangladesh" title="National University, Bangladesh">National University, Bangladesh</a>
</td>
<td><a class="mw-redirect" href="/wiki/Gazipur,_Dhaka_Division" title="Gazipur, Dhaka Division">Gazipur</a>, <a href="/wiki/Bangladesh" title="Bangladesh">Bangladesh</a>
</td>
<td>Asia
</td>
<td>1992
</td>
<td>Public
</td>
<td>In-Person
</td>
<td>3,425,832
</td>
<td><sup class="reference" id="cite_ref-4"><a href="#cite_note-4"><span class="cite-bracket">[</span>4<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>3
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/Turkey" title="Turkey"><img alt="Turkey" class="mw-file-element" data-file-height="800" data-file-width="1200" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/23px-Flag_of_Turkey.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/35px-Flag_of_Turkey.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/45px-Flag_of_Turkey.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/Anadolu_University" title="Anadolu University">Anadolu University</a>
</td>
<td><a href="/wiki/Eski%C5%9Fehir" title="Eskişehir">Eskişehir</a>, <a href="/wiki/Turkey" title="Turkey">Turkey</a>
</td>
<td>Asia
</td>
<td>1958
</td>
<td>Public
</td>
<td>Distance/In-Person
</td>
<td>1,974,343
</td>
<td><sup class="reference" id="cite_ref-5"><a href="#cite_note-5"><span class="cite-bracket">[</span>5<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>4
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/California_Community_Colleges" title="California Community Colleges">California Community Colleges</a>
</td>
<td><a href="/wiki/California" title="California">California</a>, <a href="/wiki/United_States" title="United States">United States</a>
</td>
<td>North America
</td>
<td>1967
</td>
<td>Public
</td>
<td>In-Person
</td>
<td>1,800,000
</td>
<td><sup class="reference" id="cite_ref-6"><a href="#cite_note-6"><span class="cite-bracket">[</span>6<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>5
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/Iran" title="Iran"><img alt="Iran" class="mw-file-element" data-file-height="360" data-file-width="630" decoding="async" height="13" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/40px-Flag_of_Iran.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/60px-Flag_of_Iran.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/Islamic_Azad_University" title="Islamic Azad University">Islamic Azad University</a>
</td>
<td><a href="/wiki/Iran" title="Iran">Iran</a>
</td>
<td>Asia
</td>
<td>1982
</td>
<td>Private
</td>
<td>In-Person
</td>
<td>1,778,000
</td>
<td><sup class="reference" id="cite_ref-7"><a href="#cite_note-7"><span class="cite-bracket">[</span>7<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>6
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/Pakistan" title="Pakistan"><img alt="Pakistan" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/23px-Flag_of_Pakistan.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/35px-Flag_of_Pakistan.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/45px-Flag_of_Pakistan.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/Allama_Iqbal_Open_University" title="Allama Iqbal Open University">Allama Iqbal Open University</a>
</td>
<td><a href="/wiki/Islamabad" title="Islamabad">Islamabad</a>, <a href="/wiki/Pakistan" title="Pakistan">Pakistan</a>
</td>
<td>Asia
</td>
<td>1974
</td>
<td>Public
</td>
<td>Distance/In-Person
</td>
<td>1,027,000
</td>
<td><sup class="reference" id="cite_ref-8"><a href="#cite_note-8"><span class="cite-bracket">[</span>8<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>7
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a class="mw-redirect" href="/wiki/Laureate_Education,_Inc." title="Laureate Education, Inc.">Laureate Education, Inc.</a>
</td>
<td>International
</td>
<td>Global
</td>
<td>1999
</td>
<td>Private
</td>
<td>Distance/In-Person
</td>
<td>875,000
</td>
<td><sup class="reference" id="cite_ref-9"><a href="#cite_note-9"><span class="cite-bracket">[</span>9<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>8
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/Bangladesh" title="Bangladesh"><img alt="Bangladesh" class="mw-file-element" data-file-height="307" data-file-width="512" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/23px-Flag_of_Bangladesh.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/35px-Flag_of_Bangladesh.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/46px-Flag_of_Bangladesh.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/Bangladesh_Open_University" title="Bangladesh Open University">Bangladesh Open University</a>
</td>
<td><a class="mw-redirect" href="/wiki/Gazipur,_Dhaka_Division" title="Gazipur, Dhaka Division">Gazipur</a>, <a href="/wiki/Bangladesh" title="Bangladesh">Bangladesh</a>
</td>
<td>Asia
</td>
<td>1992
</td>
<td>Public
</td>
<td>Distance
</td>
<td>650,000
</td>
<td><sup class="reference" id="cite_ref-10"><a href="#cite_note-10"><span class="cite-bracket">[</span>10<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>9
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/Indonesia" title="Indonesia"><img alt="Indonesia" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/23px-Flag_of_Indonesia.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/35px-Flag_of_Indonesia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/45px-Flag_of_Indonesia.svg.png 2x" width="23"/></a></span></span> <a class="mw-redirect" href="/wiki/Universitas_Terbuka" title="Universitas Terbuka">Universitas Terbuka</a>
</td>
<td><a href="/wiki/Jakarta" title="Jakarta">Jakarta</a>, <a href="/wiki/Indonesia" title="Indonesia">Indonesia</a>
</td>
<td>Asia
</td>
<td>1984
</td>
<td>Public
</td>
<td>Distance
</td>
<td>646,467
</td>
<td><sup class="reference" id="cite_ref-11"><a href="#cite_note-11"><span class="cite-bracket">[</span>11<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>10
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/Mexico" title="Mexico"><img alt="Mexico" class="mw-file-element" data-file-height="560" data-file-width="980" decoding="async" height="13" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/40px-Flag_of_Mexico.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/60px-Flag_of_Mexico.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/National_Technological_Institute_of_Mexico" title="National Technological Institute of Mexico">National Technological Institute of Mexico</a>
</td>
<td><a href="/wiki/Mexico" title="Mexico">Mexico</a>
</td>
<td>North America
</td>
<td>1948 and 2014
</td>
<td>Public
</td>
<td>In-Person
</td>
<td>620,000 (2019)
</td>
<td>
</td></tr>
<tr>
<td>11
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/India" title="India"><img alt="India" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/35px-Flag_of_India.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/45px-Flag_of_India.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/Savitribai_Phule_Pune_University" title="Savitribai Phule Pune University">Savitribai Phule Pune University</a>
</td>
<td><a href="/wiki/Pune" title="Pune">Pune</a>, <a href="/wiki/Maharashtra" title="Maharashtra">Maharashtra</a>, <a href="/wiki/India" title="India">India</a>
</td>
<td>Asia
</td>
<td>1948
</td>
<td>Public
</td>
<td>In-Person
</td>
<td>665,000
</td>
<td><sup class="reference" id="cite_ref-12"><a href="#cite_note-12"><span class="cite-bracket">[</span>12<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>12
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/India" title="India"><img alt="India" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/35px-Flag_of_India.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/45px-Flag_of_India.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/Chaudhary_Charan_Singh_University" title="Chaudhary Charan Singh University">Chaudhary Charan Singh University</a>
</td>
<td><a href="/wiki/Meerut" title="Meerut">Meerut</a>, <a href="/wiki/Uttar_Pradesh" title="Uttar Pradesh">Uttar Pradesh</a>, <a href="/wiki/India" title="India">India</a>
</td>
<td>Asia
</td>
<td>1965
</td>
<td>Public
</td>
<td>In-Person
</td>
<td>560,000<sup class="noprint Inline-Template Template-Fact" style="white-space:nowrap;">[<i><a href="/wiki/Wikipedia:Citation_needed" title="Wikipedia:Citation needed"><span title="No evidence of such number or anything close (May 2018)">citation needed</span></a></i>]</sup>
</td>
<td>
</td></tr>
<tr>
<td>13
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/India" title="India"><img alt="India" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/35px-Flag_of_India.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/45px-Flag_of_India.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/University_of_Mumbai" title="University of Mumbai">University of Mumbai</a>
</td>
<td><a href="/wiki/Mumbai" title="Mumbai">Mumbai</a>, <a href="/wiki/Maharashtra" title="Maharashtra">Maharashtra</a>, <a href="/wiki/India" title="India">India</a>
</td>
<td>Asia
</td>
<td>1857
</td>
<td>Public
</td>
<td>In-Person
</td>
<td>549,432
</td>
<td><sup class="reference" id="cite_ref-13"><a href="#cite_note-13"><span class="cite-bracket">[</span>13<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>14
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/Thailand" title="Thailand"><img alt="Thailand" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/23px-Flag_of_Thailand.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/35px-Flag_of_Thailand.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/45px-Flag_of_Thailand.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/Ramkhamhaeng_University" title="Ramkhamhaeng University">Ramkhamhaeng University</a>
</td>
<td><a class="mw-redirect" href="/wiki/Bangkok,_Thailand" title="Bangkok, Thailand">Bangkok, Thailand</a>
</td>
<td>Asia
</td>
<td>1971
</td>
<td>Public
</td>
<td>In-Person
</td>
<td>525,000
</td>
<td><sup class="reference" id="cite_ref-14"><a href="#cite_note-14"><span class="cite-bracket">[</span>14<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>15
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/Nigeria" title="Nigeria"><img alt="Nigeria" class="mw-file-element" data-file-height="600" data-file-width="1200" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/23px-Flag_of_Nigeria.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/35px-Flag_of_Nigeria.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/46px-Flag_of_Nigeria.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/National_Open_University_of_Nigeria" title="National Open University of Nigeria">National Open University of Nigeria</a>
</td>
<td><a href="/wiki/Nigeria" title="Nigeria">Nigeria</a>
</td>
<td>Africa
</td>
<td>2002
</td>
<td>Public
</td>
<td>Distance
</td>
<td>515,000
</td>
<td><sup class="reference" id="cite_ref-15"><a href="#cite_note-15"><span class="cite-bracket">[</span>15<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>16
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/California_State_University" title="California State University">California State University system</a>
</td>
<td><a href="/wiki/California" title="California">California</a>, <a href="/wiki/United_States" title="United States">United States</a>
</td>
<td>North America
</td>
<td>1857
</td>
<td>Public
</td>
<td>In-Person
</td>
<td>457,992
</td>
<td><sup class="reference" id="cite_ref-16"><a href="#cite_note-16"><span class="cite-bracket">[</span>16<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>17
</td>
<td><span class="flagicon"><span typeof="mw:File"><a href="/wiki/Nepal" title="Nepal"><img alt="Nepal" class="mw-file-element" data-file-height="885" data-file-width="726" decoding="async" height="20" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/20px-Flag_of_Nepal.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/40px-Flag_of_Nepal.svg.png 1.5x" width="16"/></a></span></span> <a href="/wiki/Tribhuvan_University" title="Tribhuvan University">Tribhuvan University</a>
</td>
<td><a href="/wiki/Kirtipur" title="Kirtipur">Kirtipur</a>, <a href="/wiki/Nepal" title="Nepal">Nepal</a>
</td>
<td>Asia
</td>
<td>1959
</td>
<td>Public
</td>
<td>In-Person
</td>
<td>454,065 (2021/22)
</td>
<td><sup class="reference" id="cite_ref-17"><a href="#cite_note-17"><span class="cite-bracket">[</span>17<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>18
</td>

In [152]:
trs = table.findAll(('tr'))
trs[0]

<tr>
<th>Rank
</th>
<th>Institution
</th>
<th>Location
</th>
<th>Continent
</th>
<th>Founded
</th>
<th>Affiliation
</th>
<th>Distance / In-Person<style data-mw-deduplicate="TemplateStyles:r1041539562">.mw-parser-output .citation{word-wrap:break-word}.mw-parser-output .citation:target{background-color:rgba(0,127,255,0.133)}</style><sup class="citation nobold" id="ref_distancea"><a href="#endnote_distancea">[a]</a></sup>
</th>
<th>Enrollment
</th>
<th class="unsortable">Ref
</th></tr>

In [154]:
columns = list(map(lambda x: x.text.strip(), trs[0].findAll('th')))
columns [-1] = 'link'
columns

['Rank',
 'Institution',
 'Location',
 'Continent',
 'Founded',
 'Affiliation',
 'Distance / In-Person[a]',
 'Enrollment',
 'link']

In [156]:
# to get the rolls

rows = trs[1:]
rows[0]

<tr>
<td>1
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/India" title="India"><img alt="India" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/35px-Flag_of_India.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/45px-Flag_of_India.svg.png 2x" width="23"/></a></span></span><a href="/wiki/Indira_Gandhi_National_Open_University" title="Indira Gandhi National Open University">Indira Gandhi National Open University</a>
</td>
<td><a href="/wiki/New_Delhi" title="New Delhi">New Delhi</a>, <a href="/wiki/India" title="India">India</a>
</td>
<td>Asia
</td>
<td>1985
</td>
<td>Public
</td>
<td>Distance/In-Person
</td>
<td>7,140,000+
</td>
<td><sup class="reference" id="cite_ref-1"><a href="#cite_note-1"><span class="cite-bracket">[</span>1<span class="cite-bracket">]</span></a></sup>
<p><sup class="reference" id="cite_ref-2"><a href="#cite_note-2"><span class="cite-bracket">[</span>2<span class="cite-bracket">]</span></a></sup><sup class="reference" id="cite_ref-3"><a href="#cite_note-3"><span class="cite-bracket">[</span>3<span class="cite-bracket">]</span></a></sup>
</p>
</td></tr>

In [158]:
rows[0].findAll('td')

[<td>1
 </td>,
 <td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/India" title="India"><img alt="India" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/35px-Flag_of_India.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/45px-Flag_of_India.svg.png 2x" width="23"/></a></span></span><a href="/wiki/Indira_Gandhi_National_Open_University" title="Indira Gandhi National Open University">Indira Gandhi National Open University</a>
 </td>,
 <td><a href="/wiki/New_Delhi" title="New Delhi">New Delhi</a>, <a href="/wiki/India" title="India">India</a>
 </td>,
 <td>Asia
 </td>,
 <td>1985
 </td>,
 <td>Public
 </td>,
 <td>Distance/In-Person
 </td>,
 <td>7,140,000+
 </td>,
 <td><sup class="reference" id="cite_ref-1"><a href="#cite_note-1"><span class="cite-bracket">[</span>1<span class="cite-bracket">]</span></a></sup>
 <p><sup class="reference" id="cite_ref-2"><a href="#cite_note-2"><span class="cite-bracket">[</span>2<span class="cite-bracket">]</span></a></sup><sup class="reference" id="cite_ref-3"><a href="#cite_note-3"><span class="cite-bracket">[</span>3<span class="cite-bracket">]</span></a></sup>
 </p>
 </td>]

In [160]:
rows[0].findAll('td')[1].findAll('a')[1].attrs['href'].lstrip('/')

'wiki/Indira_Gandhi_National_Open_University'

In [162]:
# def extract_rows(tr):
#     row_soup_list = tr.findAll('td')
#     row = list(map(lambda x: x.text.strip(), row_soup_list))
#     link =  row_soup_list[1].a.attrs['href'].lstrip('/')
#     row[-1] = f' https://en.wikipedia.org/{link}' if link else ' '
#     #print('link:', link)
#     return row

def extract_row(tr):
    row_soup_list = tr.findAll('td')
    row = list(map(lambda x: x.text.strip(), row_soup_list))
    link =  row_soup_list[1].findAll('a')[1].attrs['href'].lstrip('/')
    row[-1] = f' https://en.wikipedia.org/{link}' if link else ' '
    #print('link:', link)
    return row

In [105]:
extract_rows(rows[36])

['36',
 'City University of New York',
 'New York, United States',
 'North America',
 '1961',
 'Public',
 'In-Person',
 '243,000',
 ' https://en.wikipedia.org/wiki/United_States']

In [164]:
data = list(map(extract_rows, rows))

In [166]:
data

[['1',
  'Indira Gandhi National Open University',
  'New Delhi, India',
  'Asia',
  '1985',
  'Public',
  'Distance/In-Person',
  '7,140,000+',
  ' https://en.wikipedia.org/wiki/India'],
 ['2',
  'National University, Bangladesh',
  'Gazipur, Bangladesh',
  'Asia',
  '1992',
  'Public',
  'In-Person',
  '3,425,832',
  ' https://en.wikipedia.org/wiki/Bangladesh'],
 ['3',
  'Anadolu University',
  'Eskişehir, Turkey',
  'Asia',
  '1958',
  'Public',
  'Distance/In-Person',
  '1,974,343',
  ' https://en.wikipedia.org/wiki/Turkey'],
 ['4',
  'California Community Colleges',
  'California, United States',
  'North America',
  '1967',
  'Public',
  'In-Person',
  '1,800,000',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['5',
  'Islamic Azad University',
  'Iran',
  'Asia',
  '1982',
  'Private',
  'In-Person',
  '1,778,000',
  ' https://en.wikipedia.org/wiki/Iran'],
 ['6',
  'Allama Iqbal Open University',
  'Islamabad, Pakistan',
  'Asia',
  '1974',
  'Public',
  'Distance/In-Person',
  '1,027,000',
  ' https://en.wikipedia.org/wiki/Pakistan'],
 ['7',
  'Laureate Education, Inc.',
  'International',
  'Global',
  '1999',
  'Private',
  'Distance/In-Person',
  '875,000',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['8',
  'Bangladesh Open University',
  'Gazipur, Bangladesh',
  'Asia',
  '1992',
  'Public',
  'Distance',
  '650,000',
  ' https://en.wikipedia.org/wiki/Bangladesh'],
 ['9',
  'Universitas Terbuka',
  'Jakarta, Indonesia',
  'Asia',
  '1984',
  'Public',
  'Distance',
  '646,467',
  ' https://en.wikipedia.org/wiki/Indonesia'],
 ['10',
  'National Technological Institute of Mexico',
  'Mexico',
  'North America',
  '1948 and 2014',
  'Public',
  'In-Person',
  '620,000 (2019)',
  ' https://en.wikipedia.org/wiki/Mexico'],
 ['11',
  'Savitribai Phule Pune University',
  'Pune, Maharashtra, India',
  'Asia',
  '1948',
  'Public',
  'In-Person',
  '665,000',
  ' https://en.wikipedia.org/wiki/India'],
 ['12',
  'Chaudhary Charan Singh University',
  'Meerut, Uttar Pradesh, India',
  'Asia',
  '1965',
  'Public',
  'In-Person',
  '560,000[citation needed]',
  ' https://en.wikipedia.org/wiki/India'],
 ['13',
  'University of Mumbai',
  'Mumbai, Maharashtra, India',
  'Asia',
  '1857',
  'Public',
  'In-Person',
  '549,432',
  ' https://en.wikipedia.org/wiki/India'],
 ['14',
  'Ramkhamhaeng University',
  'Bangkok, Thailand',
  'Asia',
  '1971',
  'Public',
  'In-Person',
  '525,000',
  ' https://en.wikipedia.org/wiki/Thailand'],
 ['15',
  'National Open University of Nigeria',
  'Nigeria',
  'Africa',
  '2002',
  'Public',
  'Distance',
  '515,000',
  ' https://en.wikipedia.org/wiki/Nigeria'],
 ['16',
  'California State University system',
  'California, United States',
  'North America',
  '1857',
  'Public',
  'In-Person',
  '457,992',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['17',
  'Tribhuvan University',
  'Kirtipur, Nepal',
  'Asia',
  '1959',
  'Public',
  'In-Person',
  '454,065 (2021/22)',
  ' https://en.wikipedia.org/wiki/Nepal'],
 ['18',
  'University of the Punjab',
  'Lahore, Punjab, Pakistan',
  'Asia',
  '1882',
  'Public',
  'In-Person',
  '450,000',
  ' https://en.wikipedia.org/wiki/Pakistan'],
 ['19',
  'Dr. B R Ambedkar Open University',
  'Telangana, India',
  'Asia',
  '1982',
  'Public',
  'Distance',
  '450,000',
  ' https://en.wikipedia.org/wiki/India'],
 ['20',
  'State University System of Florida',
  'Florida, United States',
  'North America',
  '1954',
  'Public',
  'In-Person',
  '430,000',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['21',
  'University System of Ohio',
  'Ohio, United States',
  'North America',
  '2007',
  'Public',
  'In-Person',
  '429,310',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['22',
  'University of Delhi',
  'Delhi, India',
  'Asia',
  '1922',
  'Public',
  'In-Person/Distance',
  '700,000',
  ' https://en.wikipedia.org/wiki/India'],
 ['23',
  'Payame Noor University',
  'Iran',
  'Asia',
  '1987',
  'Public',
  'Distance/In-Person',
  '400,000',
  ' https://en.wikipedia.org/wiki/Iran'],
 ['24',
  'Sikkim Manipal University',
  'Sikkim, India',
  'Asia',
  '1995',
  'Private',
  'In-Person',
  '390,000',
  ' https://en.wikipedia.org/wiki/India'],
 ['25',
  'University of South Africa',
  'Pretoria, Gauteng, South Africa',
  'Africa',
  '1873',
  'Public',
  'Distance',
  '370 000',
  ' https://en.wikipedia.org/wiki/South_Africa'],
 ['26',
  'State University of New York system',
  'New York, United States',
  'North America',
  '1948',
  'Public',
  'In-Person',
  '363,612',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['27',
  'National Autonomous University of Mexico',
  'Mexico City, Mexico',
  'North America',
  '1551',
  'Public',
  'In-Person',
  '356,530',
  ' https://en.wikipedia.org/wiki/Mexico'],
 ['28',
  'National Centre for Distance Education',
  'France',
  'Europe',
  '1939',
  'Public',
  'Distance',
  '350,000',
  ' https://en.wikipedia.org/wiki/France'],
 ['29',
  'University System of Georgia',
  'Georgia, United States',
  'North America',
  '1931',
  'Public',
  'In-Person',
  '318,027',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['30',
  'University of Buenos Aires',
  'Buenos Aires, Argentina',
  'South America',
  '1821',
  'Public',
  'In-Person',
  '316,050',
  ' https://en.wikipedia.org/wiki/Argentina'],
 ['30',
  'Minnesota State Colleges and Universities',
  'Minnesota, United States',
  'North America',
  '1995',
  'Public',
  'In-Person',
  '300,000',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['31',
  'Osmania University',
  'Hyderabad, Telangana, India',
  'Asia',
  '1918',
  'Public',
  'In-Person',
  '300,000',
  ' https://en.wikipedia.org/wiki/India'],
 ['32',
  'National University of Distance Education',
  'Spain',
  'Europe',
  '1972',
  'Public',
  'Distance/In-Person',
  '260,079',
  ' https://en.wikipedia.org/wiki/Spain'],
 ['33',
  'Rajiv Gandhi Technical University',
  'Bhopal, Madhya Pradesh, India',
  'Asia',
  '1998',
  'Public',
  'In-Person',
  '260,000',
  ' https://en.wikipedia.org/wiki/India'],
 ['34',
  'Cairo University',
  'Giza, Egypt',
  'Africa',
  '1908',
  'Public',
  'In-Person',
  '257,200',
  ' https://en.wikipedia.org/wiki/Egypt'],
 ['35',
  'University of California system',
  'California, United States',
  'North America',
  '1869',
  'Public',
  'In-Person',
  '256,000',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['36',
  'City University of New York',
  'New York, United States',
  'North America',
  '1961',
  'Public',
  'In-Person',
  '243,000',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['37',
  'University of North Carolina system',
  'North Carolina, United States',
  'North America',
  '1789',
  'Public',
  'In-Person',
  '242,000',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['38',
  'University of Texas System',
  'Texas, United States',
  'North America',
  '1881',
  'Public',
  'In-Person',
  '221,337',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['39',
  'Estácio de Sá University',
  'Rio de Janeiro, Rio de Janeiro, Brazil',
  'South America',
  '1970',
  'Private',
  'In-Person',
  '215,000',
  ' https://en.wikipedia.org/wiki/Brazil'],
 ['40',
  'University of Guadalajara',
  'Guadalajara, Jalisco, Mexico',
  'North America',
  '1791',
  'Public',
  'In-Person',
  '209,406',
  ' https://en.wikipedia.org/wiki/Mexico'],
 ['41',
  'University of Nuevo León',
  'Monterrey, Nuevo León, Mexico',
  'North America',
  '1933',
  'Public',
  'In-Person',
  '206,000',
  ' https://en.wikipedia.org/wiki/Mexico'],
 ['42',
  'Open University',
  'Milton Keynes, United Kingdom',
  'Europe',
  '1969',
  'Public',
  'Distance/In-Person',
  '205,420',
  ' https://en.wikipedia.org/wiki/United_Kingdom'],
 ['43',
  'University of Applied Science and Technology',
  'Iran',
  'Asia',
  '1992',
  'Public',
  'In-Person',
  '200,000',
  ' https://en.wikipedia.org/wiki/Iran'],
 ['44',
  'Technical College System of Georgia',
  'Georgia, United States',
  'North America',
  '1970',
  'Public',
  'In-Person',
  '191,567',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['45',
  'Utah System of Higher Education',
  'Utah, United States',
  'North America',
  '1894',
  'Public',
  'In-Person',
  '189,351',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['46',
  'Russian Presidential Academy of National Economy and Public Administration',
  'Moscow, Russian Federation',
  'Europe',
  '1977',
  'Public',
  'In-Person',
  '180,000',
  ' https://en.wikipedia.org/wiki/Russia'],
 ['47',
  'King Abdulaziz University',
  'Jeddah, Saudi Arabia',
  'Asia',
  '1976',
  'Public',
  'In-Person',
  '177,234',
  ' https://en.wikipedia.org/wiki/Saudi_Arabia'],
 ['48',
  'Technical and Vocational University',
  'Iran',
  'Asia',
  '1965',
  'Public',
  'In-Person',
  '175,000',
  ' https://en.wikipedia.org/wiki/Iran'],
 ['49',
  'National Polytechnic Institute',
  'Mexico City, Mexico',
  'North America',
  '1936',
  'Public',
  'In-Person',
  '171,581',
  ' https://en.wikipedia.org/wiki/Mexico'],
 ['50',
  'Autonomous University of Santo Domingo',
  'Santo Domingo',
  'North America',
  '1538 (reopened 1914)',
  'Public',
  'In-Person',
  '170,530',
  ' https://en.wikipedia.org/wiki/Dominican_Republic'],
 ['51',
  'Ain Shams University',
  'Cairo, Egypt',
  'Africa',
  '1950',
  'Public',
  'In-Person',
  '170,000 (Undergraduates Only)',
  ' https://en.wikipedia.org/wiki/Egypt'],
 ['52',
  'University of London',
  'London, United Kingdom',
  'Europe',
  '1836',
  'Public',
  'In-Person',
  '170,000',
  ' https://en.wikipedia.org/wiki/United_Kingdom'],
 ['53',
  'Southern New Hampshire University',
  'New Hampshire, United States',
  'North America',
  '1932',
  'Private',
  'Distance / In-person',
  '170,000',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['54',
  'Illinois Board of Higher Education',
  'Illinois, United States',
  'North America',
  '1862',
  'Public',
  'In-Person',
  '163,786',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['55',
  'University of Wisconsin System',
  'Wisconsin, United States',
  'North America',
  '1848',
  'Public',
  'In-Person',
  '162,933',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['56',
  'Universiti Teknologi MARA',
  'Shah Alam, Malaysia',
  'Asia',
  '1956',
  'Public',
  'In-Person',
  '160,957',
  ' https://en.wikipedia.org/wiki/Malaysia'],
 ['57',
  'University of the People',
  'California, United States',
  'North America',
  '2009',
  'Private',
  'Distance',
  '152,000',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['58',
  'Korea National Open University',
  'South Korea',
  'Asia',
  '1972',
  'Public',
  'Distance/In-Person',
  '151,413',
  ' https://en.wikipedia.org/wiki/South_Korea'],
 ['59',
  'Dr. A.P.J. Abdul Kalam Technical University',
  'Lucknow, Uttar Pradesh, India',
  'Asia',
  '2000',
  'Public',
  'In-Person',
  '150,000',
  ' https://en.wikipedia.org/wiki/India'],
 ['60',
  'Madhya Pradesh Bhoj Open University',
  'Bhopal, Madhya Pradesh, India',
  'Asia',
  '1991',
  'Public',
  'Distance',
  '150,000',
  ' https://en.wikipedia.org/wiki/India'],
 ['61',
  'Sapienza University of Rome',
  'Rome, Italy',
  'Europe',
  '1303',
  'Public',
  'In-Person',
  '147,000',
  ' https://en.wikipedia.org/wiki/Italy'],
 ['62',
  'University System of Maryland',
  'Maryland, United States',
  'North America',
  '1988',
  'Public',
  'In-Person',
  '144,363',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['63',
  'University of the Republic',
  'Montevideo, Uruguay',
  'South America',
  '1849',
  'Public',
  'In-Person',
  '144,108',
  ' https://en.wikipedia.org/wiki/Uruguay'],
 ['64',
  'Norte do Paraná University',
  'Londrina, Paraná, Brazil',
  'South America',
  '1972',
  'Private',
  'Distance/In-Person',
  '130,000',
  ' https://en.wikipedia.org/wiki/Brazil'],
 ['65',
  'IU International University of Applied Sciences',
  'Erfurt, Germany',
  'Europe',
  '1998',
  'Private',
  'Distance/In-Person',
  '130,000',
  ' https://en.wikipedia.org/wiki/Germany'],
 ['66',
  'University of San Carlos of Guatemala',
  'Guatemala City, Guatemala',
  'North America',
  '1676',
  'Public',
  'In-Person',
  '124,000',
  ' https://en.wikipedia.org/wiki/Guatemala'],
 ['67',
  'University of Lyon',
  'Lyon, France',
  'Europe',
  '2007',
  'Public',
  'In-Person',
  '120,000',
  ' https://en.wikipedia.org/wiki/France'],
 ['68',
  'UNIMINUTO system',
  'Colombia',
  'South America',
  '1990',
  'Private',
  'Distance/In-Person',
  '116,782',
  ' https://en.wikipedia.org/wiki/Colombia'],
 ['69',
  'Texas A&M University System',
  'Texas, United States',
  'North America',
  '1876',
  'Public',
  'In-Person',
  '114,691',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['70',
  'National University of Córdoba',
  'Córdoba, Argentina',
  'South America',
  '1613',
  'Public',
  'In-Person',
  '113,558',
  ' https://en.wikipedia.org/wiki/Argentina'],
 ['71',
  'Pennsylvania State System of Higher Education',
  'Pennsylvania, United States',
  'North America',
  '1982',
  'Public',
  'In-Person',
  '110,428',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['72',
  'Liberty University',
  'Virginia, United States',
  'North America',
  '1971',
  'Private',
  'Distance/In-Person',
  '110,000',
  ' https://en.wikipedia.org/wiki/United_States'],
 ['73',
  'University of Toulouse',
  'Toulouse, France',
  'Europe',
  '1229',
  'Public',
  'In-Person',
  '110,000',
  ' https://en.wikipedia.org/wiki/France'],
 ['74',
  'Université du Québec',
  'Quebec, Canada',
  'North America',
  '1968',
  'Public',
  'In-Person/ Distance',
  '101,915',
  ' https://en.wikipedia.org/wiki/Canada'],
 ['75',
  'Virtual University of Pakistan',
  'Lahore, Islamabad, Pakistan',
  'Asia',
  '2002',
  'Public',
  'Distance',
  '100,000',
  ' https://en.wikipedia.org/wiki/Pakistan'],
 ['76',
  'Vietnam National University, Ho Chi Minh City',
  'Ho Chi Minh City, Vietnam',
  'Asia',
  '1995',
  'Public',
  'In-Person',
  '98,648',
  ' https://en.wikipedia.org/wiki/Vietnam'],
 ['77',
  'University of Belgrade',
  'Belgrade, Serbia',
  'Europe',
  '1808',
  'Public',
  'In-Person',
  '97,696',
  ' https://en.wikipedia.org/wiki/Serbia'],
 ['78',
  'University of Vienna',
  'Vienna, Austria',
  'Europe',
  '1365',
  'Public',
  'In-Person',
  '91,715',
  ' https://en.wikipedia.org/wiki/Austria'],
 ['79',
  'Monterrey Institute of Technology and Higher Education',
  'Monterrey, Nuevo León, Mexico',
  'North America',
  '1943',
  'Private',
  'In-Person',
  '91,200',
  ' https://en.wikipedia.org/wiki/Mexico'],
 ['80',
  'University of Toronto',
  'Toronto, Canada',
  'North America',
  '1827',
  'Public',
  'In-Person',
  '88,766',
  ' https://en.wikipedia.org/wiki/Canada'],
 ['81',
  'Aristotle University of Thessaloniki',
  'Thessaloniki, Greece',
  'Europe',
  '1925',
  'Public',
  'In-Person',
  '88,283',
  ' https://en.wikipedia.org/wiki/Greece'],
 ['82',
  'Polytechnic University of the Philippines',
  'Philippines',
  'Asia',
  '1904',
  'Public',
  'Distance/In-Person',
  '83,328',
  ' https://en.wikipedia.org/wiki/Philippines'],
 ['83',
  'Complutense University of Madrid',
  'Madrid, Spain',
  'Europe',
  '1293',
  'Public',
  'In-Person',
  '83,000',
  ' https://en.wikipedia.org/wiki/Spain'],
 ['84',
  'Farhangian University',
  'Iran',
  'Asia',
  '2012',
  'Public',
  'In-Person',
  '80,000',
  ' https://en.wikipedia.org/wiki/Iran'],
 ['85',
  'Aix-Marseille University',
  'Marseille, France',
  'Europe',
  '1409',
  'Public',
  'In-Person',
  '80,000',
  ' https://en.wikipedia.org/wiki/France'],
 ['86',
  'University of Hagen',
  'Hagen, Germany',
  'Europe',
  '1974',
  'Public',
  'Distance',
  '69,982',
  ' https://en.wikipedia.org/wiki/Germany'],
 ['87',
  'Université de Montréal',
  'Canada',
  'North America',
  '1878',
  'Public',
  'Distance/In-Person',
  '67,109',
  ' https://en.wikipedia.org/wiki/Canada'],
 ['88',
  'University of the Philippines',
  'Philippines',
  'Asia',
  '1908',
  'Public',
  'Distance/In-Person',
  '64,144',
  ' https://en.wikipedia.org/wiki/Philippines'],
 ['89',
  'Academic Center for Education, Culture and Research',
  'Iran',
  'Asia',
  '1980',
  'Private',
  'In-Person',
  '60,000',
  ' https://en.wikipedia.org/wiki/Iran']]

In [168]:
df = pd.DataFrame(data = data, columns = columns)

In [170]:
df

,Rank,Institution,Location,Continent,Founded,Affiliation,Distance / In-Person[a],Enrollment,link
0,1,Indira Gandhi National Open University,"New Delhi, India",Asia,1985,Public,Distance/In-Person,"7,140,000+",https://en.wikipedia.org/wiki/India
1,2,"National University, Bangladesh","Gazipur, Bangladesh",Asia,1992,Public,In-Person,"3,425,832",https://en.wikipedia.org/wiki/Bangladesh
2,3,Anadolu University,"Eskişehir, Turkey",Asia,1958,Public,Distance/In-Person,"1,974,343",https://en.wikipedia.org/wiki/Turkey
3,4,California Community Colleges,"California, United States",North America,1967,Public,In-Person,"1,800,000",https://en.wikipedia.org/wiki/United_States
4,5,Islamic Azad University,Iran,Asia,1982,Private,In-Person,"1,778,000",https://en.wikipedia.org/wiki/Iran
...,...,...,...,...,...,...,...,...,...
85,85,Aix-Marseille University,"Marseille, France",Europe,1409,Public,In-Person,"80,000",https://en.wikipedia.org/wiki/France
86,86,University of Hagen,"Hagen, Germany",Europe,1974,Public,Distance,"69,982",https://en.wikipedia.org/wiki/Germany
87,87,Université de Montréal,Canada,North America,1878,Public,Distance/In-Person,"67,109",https://en.wikipedia.org/wiki/Canada
88,88,University of the Philippines,Philippines,Asia,1908,Public,Distance/In-Person,"64,144",https://en.wikipedia.org/wiki/Philippines
89,89,"Academic Center for Education, Culture and Res...",Iran,Asia,1980,Private,In-Person,"60,000",https://en.wikipedia.org/wiki/Iran

In [67]:
df.columns

Index(['Rank', 'Institution', 'Location', 'Continent', 'Founded',
       'Affiliation', 'Distance / In-Person[a]', 'Enrollment', 'link'],
      dtype='object')

FactUniversityStats
├── Rank
├── Enrollment
├── institution_id (FK → dimInstitution)
├── location_id (FK → dimLocation)
├── affiliation_id (FK → dimAffiliation)
└── delivery_mode_id (FK → dimDeliveryMode)

dimInstitution
├── institution_id (PK)
├── Institution
├── Founded
└── link

dimLocation
├── location_id (PK)
├── Location
└── Continent

dimAffiliation
├── affiliation_id (PK)
└── Affiliation

dimDeliveryMode
├── delivery_mode_id (PK)
└── Distance / In-Person

dimcontinenet
├── continent_id (PK)
└── continenet_name

In [172]:
df.rename(columns={'Distance / In-Person[a]': 'learning_mode'}, inplace=True)

df.rename(columns={'Continent': 'continenent_name'}, inplace=True)

In [174]:
df.rename(columns={'Affiliation': 'affiliate_Type'}, inplace=True)

In [176]:
df['founded_year'] = df['Founded'].str.extract(r'(\d{4})')

df['founded_year'] = df['founded_year'].astype(int)

In [ ]:
df['clean_enrollment'] = df['Enrollment'].str.extract(r'([\d,]+)')  # extract number part
df['clean_enrollment'] = df['clean_enrollment'].str.replace(',', '', regex=False).astype(int)

In [182]:
df

,Rank,Institution,Location,continenent_name,affiliate_Type,learning_mode,link,founded_year,clean_enrollment
0,1,Indira Gandhi National Open University,"New Delhi, India",Asia,Public,Distance/In-Person,https://en.wikipedia.org/wiki/India,1985,7140000
1,2,"National University, Bangladesh","Gazipur, Bangladesh",Asia,Public,In-Person,https://en.wikipedia.org/wiki/Bangladesh,1992,3425832
2,3,Anadolu University,"Eskişehir, Turkey",Asia,Public,Distance/In-Person,https://en.wikipedia.org/wiki/Turkey,1958,1974343
3,4,California Community Colleges,"California, United States",North America,Public,In-Person,https://en.wikipedia.org/wiki/United_States,1967,1800000
4,5,Islamic Azad University,Iran,Asia,Private,In-Person,https://en.wikipedia.org/wiki/Iran,1982,1778000
...,...,...,...,...,...,...,...,...,...
85,85,Aix-Marseille University,"Marseille, France",Europe,Public,In-Person,https://en.wikipedia.org/wiki/France,1409,80000
86,86,University of Hagen,"Hagen, Germany",Europe,Public,Distance,https://en.wikipedia.org/wiki/Germany,1974,69982
87,87,Université de Montréal,Canada,North America,Public,Distance/In-Person,https://en.wikipedia.org/wiki/Canada,1878,67109
88,88,University of the Philippines,Philippines,Asia,Public,Distance/In-Person,https://en.wikipedia.org/wiki/Philippines,1908,64144
89,89,"Academic Center for Education, Culture and Res...",Iran,Asia,Private,In-Person,https://en.wikipedia.org/wiki/Iran,1980,60000

In [ ]:
# Simple solution to standardize all combined formats to 'Distance/In-Person'
df['learning_modes'] = np.where(
    (df['learning_mode'].str.lower().str.contains('distance')) & 
    (df['learning_mode'].str.lower().str.contains('in-person')),
    'Distance/In-Person',
    df['learning_mode']
)

In [ ]:
df.drop(['Founded', 'Enrollment', 'learning_mode'], axis=1, inplace=True)

In [ ]:
## Normalizing the dataframe

In [188]:
dim_affiliate = df[['affiliate_Type']].drop_duplicates().reset_index(drop=True)
dim_affiliate['affiliate_id']= dim_affiliate.index +1

df = df.merge(dim_affiliate[['affiliate_Type', 'affiliate_id']],
        on= ['affiliate_Type'],
        how='left'
             )

dim_affiliate

  affiliate_Type  affiliate_id
0         Public             1
1        Private             2

In [261]:
learningMode = df[['learning_modes']].drop_duplicates().reset_index(drop=True)
learningMode['learning_mode_id']= learningMode.index +1

df = df.merge(learningMode[['learning_modes', 'learning_mode_id']],
        on= ['learning_modes'],
        how='left'
             )
learningMode

       learning_modes  learning_mode_id
0  Distance/In-Person                 1
1           In-Person                 2
2            Distance                 3

In [266]:
continent = df[['continenent_name']].drop_duplicates().reset_index(drop=True)
continent['continent_id']= continent.index +1

df = df.merge(continent[['continenent_name', 'continent_id']],
        on= ['continenent_name'],
        how='left'
             )
continent

  continenent_name  continent_id
0             Asia             1
1    North America             2
2           Global             3
3           Africa             4
4           Europe             5
5    South America             6

In [268]:
location = df[['Location']].drop_duplicates().reset_index(drop=True)
location['location_id']= location.index +1

df = df.merge(location[['Location', 'location_id']],
        on= ['Location'],
        how='left'
             )
location

                     Location  location_id
0            New Delhi, India            1
1         Gazipur, Bangladesh            2
2           Eskişehir, Turkey            3
3   California, United States            4
4                        Iran            5
..                        ...          ...
69                Philippines           70
70              Madrid, Spain           71
71          Marseille, France           72
72             Hagen, Germany           73
73                     Canada           74

[74 rows x 2 columns]

In [282]:
institution = df[['Institution', 'founded_year','link' ]].drop_duplicates().reset_index(drop=True)
institution['institution_id']= institution.index +1

df = df.merge(institution[['Institution', 'founded_year','link', 'institution_id' ]],
        on= ['Institution', 'founded_year','link' ],
        how='left'
             )
institution

,Institution,founded_year,link,institution_id
0,Indira Gandhi National Open University,1985,https://en.wikipedia.org/wiki/India,1
1,"National University, Bangladesh",1992,https://en.wikipedia.org/wiki/Bangladesh,2
2,Anadolu University,1958,https://en.wikipedia.org/wiki/Turkey,3
3,California Community Colleges,1967,https://en.wikipedia.org/wiki/United_States,4
4,Islamic Azad University,1982,https://en.wikipedia.org/wiki/Iran,5
...,...,...,...,...
85,Aix-Marseille University,1409,https://en.wikipedia.org/wiki/France,86
86,University of Hagen,1974,https://en.wikipedia.org/wiki/Germany,87
87,Université de Montréal,1878,https://en.wikipedia.org/wiki/Canada,88
88,University of the Philippines,1908,https://en.wikipedia.org/wiki/Philippines,89
89,"Academic Center for Education, Culture and Res...",1980,https://en.wikipedia.org/wiki/Iran,90

In [ ]:
FactUniversityStats
├── Rank
├── Enrollment
├── institution_id (FK → dimInstitution)
├── location_id (FK → dimLocation)
├── affiliation_id (FK → dimAffiliation)
└── delivery_mode_id (FK → dimDeliveryMode)

In [286]:
factUniversityStats = df[['Rank', 'clean_enrollment', 'institution_id', 'continent_id', 'location_id', 'affiliate_id', 'learning_mode_id']]
factUniversityStats

,Rank,clean_enrollment,institution_id,continent_id,location_id,affiliate_id,learning_mode_id
0,1,7140000,1,1,1,1,1
1,2,3425832,2,1,2,1,2
2,3,1974343,3,1,3,1,1
3,4,1800000,4,2,4,1,2
4,5,1778000,5,1,5,2,2
...,...,...,...,...,...,...,...
85,85,80000,86,5,72,1,2
86,86,69982,87,5,73,1,3
87,87,67109,88,2,74,1,1
88,88,64144,89,1,70,1,1
89,89,60000,90,1,5,2,2

In [ ]:
## creating table

In [ ]:
def create_tables():
    conn = get_connection()
    cursor = conn.cursor()

    # Create schema
    create_schema = '''
        CREATE SCHEMA IF NOT EXISTS zapco;
    '''

    # Drop existing tables and create new ones
    create_tables = '''
        DROP TABLE IF EXISTS zapco.date_dim CASCADE;
        DROP TABLE IF EXISTS zapco.location_dim CASCADE;
        DROP TABLE IF EXISTS zapco.owner_dim CASCADE;
        DROP TABLE IF EXISTS zapco.property_dim CASCADE;
        DROP TABLE IF EXISTS zapco.property_fact CASCADE;

        CREATE TABLE zapco.date_dim (
            year INT,
            month_name TEXT,
            quarter INT,
            lastSaleDate DATE,
            date_id INT PRIMARY KEY
        );

        CREATE TABLE zapco.location_dim (
            addressLine1 TEXT,
            city TEXT,
            state TEXT,
            zipCode INT,
            county TEXT,
            latitude FLOAT,
            longitude FLOAT,
            zoning TEXT,
            subdivision TEXT,
            location_id INT PRIMARY KEY
        );

        CREATE TABLE zapco.owner_dim (
            owners_name TEXT,
            owner_type TEXT,
            ownerOccupied FLOAT, 
            owner_id INT PRIMARY KEY
        );

        CREATE TABLE zapco.property_dim (
            propertyType TEXT,
            features TEXT,
            bathrooms FLOAT,
            bedrooms FLOAT,
            squareFootage FLOAT,
            lotSize FLOAT,
            yearBuilt FLOAT,
            assessorID TEXT,
            legalDescription TEXT,
            property_id INT PRIMARY KEY
        );
        CREATE TABLE zapco.property_fact(
            fact_id SERIAL PRIMARY KEY,
            date_id INT REFERENCES zapco.date_dim(date_id),
            location_id INT REFERENCES zapco.location_dim(location_id),
            owner_id INT REFERENCES zapco.owner_dim(owner_id),
            property_id INT REFERENCES zapco.property_dim(property_id),
            taxAssessments_2022_value NUMERIC,
            taxAssessments_2023_value NUMERIC,
            propertyTaxes_2022_total NUMERIC,
            propertyTaxes_2023_total NUMERIC,
            lastSalePrice NUMERIC,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
            
    
    '''
    
    try:
        print("Creating Schema....")
        cursor.execute(create_schema)
        
        print("Creating tables...")
        cursor.execute(create_tables)

        conn.commit()
        print("All tables created successfully")
              
    except Exception as e:
        print(f"Error occurred during the table creation: {e}")
    
    finally:
        cursor.close()
        conn.close()
        print("Database connection closed")

create_tables()

In [ ]:
def load_data(csv_file_path, table_name, column_names):
    conn= get_connection()
    cursor= conn.cursor()
    with open(csv_file_path, 'r', encoding='utf-8') as file:
        reader= csv.reader(file)
        next(reader)
        for row in reader:
            placeholder =', '.join(['%s'] *len(row))
            query= f' INSERT INTO {table_name} ({", ".join(column_names)}) VALUES({placeholder});'

            cursor.execute(query, row)
    conn.commit()
    cursor.close()
    conn.close()
    print(f' dataset loaded successfully into the {table_name}')